### DISCUSSION TITLE
Problem on Inference my multi speaker model

### DISCUSSION THREAD

**Discussion by kin0303** [espnet/espnet#4723] [Q&A] [answered]
I want to Inference my multi speaker model, but text2speech.use_sids is false. So I can't change the sids. Is the train I did wrong?

My run.sh:
```
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

./tts.sh \
     --stage 6 \
     --stop_stage 6 \
     --train_args "--batch_bins 500000 --batch_type length --max_epoch 3000" \
     --ngpu 1 \
     --skip_eval true \
     --nj 6 \
     --inference_nj 6 \
     --audio_format wav \
     --use_sid true \
     --use_xvector true \
     --train_set train \
     --valid_set val \
     --test_sets test \
     --srctexts "data/train/text" "$@"
```

My config.yaml:
```
config: /media/DATA-2/TTS/Espnet/espnet/egs2/vctk/tts1/conf/train.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/tts_train_raw_phn_tacotron_g2p_en_batch_bins500000_batch_typelength_max_epoch3000
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: 0
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 3000
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
keep_nbest_models: 5
nbest_averaging_interval: 0
grad_clip: 1.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: 500
batch_size: 20
valid_batch_size: null
batch_bins: 500000
valid_batch_bins: null
train_shape_file:
- exp/tts_stats_raw_phn_tacotron_g2p_en/train/text_shape.phn
- exp/tts_stats_raw_phn_tacotron_g2p_en/train/speech_shape
valid_shape_file:
- exp/tts_stats_raw_phn_tacotron_g2p_en/valid/text_shape.phn
- exp/tts_stats_raw_phn_tacotron_g2p_en/valid/speech_shape
batch_type: length
valid_batch_type: null
fold_length:
- 150
- 204800
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train/text
    - text
    - text
-   - dump/raw/train/wav.scp
    - speech
    - sound
-   - dump/xvector/train/xvector.scp
    - spembs
    - kaldi_ark
-   - dump/raw/train/utt2sid
    - sids
    - text_int
valid_data_path_and_name_and_type:
-   - dump/raw/val/text
    - text
    - text
-   - dump/raw/val/wav.scp
    - speech
    - sound
-   - dump/xvector/val/xvector.scp
    - spembs
    - kaldi_ark
-   - dump/raw/val/utt2sid
    - sids
    - text_int
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.001
    eps: 1.0e-06
    weight_decay: 0.0
scheduler: null
scheduler_conf: {}
token_list:
- <blank>
- <unk>
- ''
- AH0
- N
- K
- T
- M
- S
- D
- L
- AE1
- P
- R
- EH1
- AA1
- B
- IY0
- NG
- IH0
- Y
- G
- UW1
- IY1
- IH1
- ER0
- JH
- ','
- EY1
- UW0
- .
- HH
- EH2
- AA0
- AY1
- EH0
- OW1
- AE0
- W
- AH1
- Z
- ER1
- OW0
- F
- AE2
- V
- AO1
- UW2
- AA2
- IH2
- ZH
- SH
- EY0
- AW0
- CH
- '?'
- UH1
- EY2
- AH2
- AO0
- OW2
- AY2
- TH
- AY0
- IY2
- AO2
- AW1
- ER2
- OY0
- OY1
- '!'
- UH0
- DH
- AW2
- UH2
- OY2
- ''''
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: phn
bpemodel: null
non_linguistic_symbols: null
cleaner: tacotron
g2p: g2p_en
feats_extract: fbank
feats_extract_conf:
    n_fft: 1024
    hop_length: 256
    win_length: null
    fs: 16000
    fmin: 80
    fmax: 7600
    n_mels: 80
normalize: global_mvn
normalize_conf:
    stats_file: exp/tts_stats_raw_phn_tacotron_g2p_en/train/feats_stats.npz
tts: tacotron2
tts_conf:
    embed_dim: 512
    elayers: 1
    eunits: 512
    econv_layers: 3
    econv_chans: 512
    econv_filts: 5
    atype: location
    adim: 512
    aconv_chans: 32
    aconv_filts: 15
    cumulate_att_w: true
    dlayers: 2
    dunits: 1024
    prenet_layers: 2
    prenet_units: 256
    postnet_layers: 5
    postnet_chans: 512
    postnet_filts: 5
    output_activation: null
    use_batch_norm: true
    use_concate: true
    use_residual: false
    use_gst: true
    gst_heads: 8
    gst_tokens: 128
    dropout_rate: 0.5
    zoneout_rate: 0.1
    reduction_factor: 1
    spk_embed_dim: null
    use_masking: true
    bce_pos_weight: 10.0
    use_guided_attn_loss: true
    guided_attn_loss_sigma: 0.4
    guided_attn_loss_lambda: 1.0
pitch_extract: null
pitch_extract_conf: {}
pitch_normalize: null
pitch_normalize_conf: {}
energy_extract: null
energy_extract_conf: {}
energy_normalize: null
energy_normalize_conf: {}
required:
- output_dir
- token_list
version: '202207'
distributed: false
```

I'm training the model using:
```
./run.sh --train_config /media/DATA-2/TTS/Espnet/espnet/egs2/vctk/tts1/conf/train.yaml
```
How I do the inference:
```
from espnet2.bin.tts_inference import Text2Speech

text2speech = Text2Speech(
    train_config="/media/DATA-2/TTS/Espnet/espnet/egs2/Tacotron2/tts1/exp/tts_train_raw_phn_tacotron_g2p_en_batch_size8_max_epoch3000/config.yaml",
    model_file="/media/DATA-2/TTS/Espnet/espnet/egs2/Tacotron2/tts1/exp/tts_train_raw_phn_tacotron_g2p_en_batch_size8_max_epoch3000/latest.pth")

import glob
import os
import numpy as np
import kaldiio

# X-vector selection
spembs = None
if text2speech.use_spembs:
    xvector_ark = [p for p in glob.glob(f"/media/DATA-2/TTS/Espnet/espnet/egs2/Tacotron2/tts1/dump/xvector/train/spk_xvector.ark", recursive=True) if "tr" in p][0]
    xvectors = {k: v for k, v in kaldiio.load_ark(xvector_ark)}
    spks = list(xvectors.keys())

    # randomly select speaker
    random_spk_idx = np.random.randint(0, len(spks))
    spk = spks[random_spk_idx]
    spembs = xvectors[spk]
    print(f"selected spk: {spk}")
# Speaker ID selection
sids = None
if text2speech.use_sids:
    spk2sid = glob.glob(f"/media/DATA-2/TTS/Espnet/espnet/egs2/Tacotron2/tts1/dump/raw/org/train/spk2sid", recursive=True)[0]
    with open(spk2sid) as f:
        lines = [line.strip() for line in f.readlines()]
    sid2spk = {int(line.split()[1]): line.split()[0] for line in lines}
    spk = sid2spk[int(sids)]
    print(f"selected spk: {spk}")
    
    # randomly select speaker
    sids = np.array(np.random.randint(1, len(sid2spk)))
    spk = sid2spk[int(sids)]
    print(f"selected spk: {spk}")
# Reference speech selection for GST
speech = None
if text2speech.use_speech:
    # you can change here to load your own reference speech
    # e.g.
    # import soundfile as sf
    # speech, fs = sf.read("/path/to/reference.wav")
    # speech = torch.from_numpy(speech).float()
    speech = torch.randn(50000,) * 0.01
import time
import torch

# decide the input sentence by yourself
x = "Apa kabar Luna?"

# synthesis
with torch.no_grad():
    start = time.time()
    wav = text2speech(x, speech=speech, spembs=spembs, sids=sids)["wav"]
rtf = (time.time() - start) / (len(wav) / text2speech.fs)
print(f"RTF = {rtf:5f}")

# let us listen to generated samples
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=text2speech.fs))
```
Should I change use_sid: true in tts.sh? Or this problem occurs because spks have not been defined?
