### ISSUE TITLE
New style to describe input features

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#1012]
I'd like to discuss about inputting data format for training program.

We encountered some issues with the current style of `data.json` now and I also feel some limitations about [LoadInputsAndTargets](https://github.com/espnet/espnet/blob/master/espnet/utils/io_utils.py) to describe training set.

#533

-  About JSON
    - JSON used much memory if the text file is too large because JSON doesn't support lazy loading.
    - The parse speed of JSON is slower than binary format, e.g. HDF5. This is critical problem if training corpus is very large.
- About `LoadInputsAndTarget`
    - `LoadInputsAndTarget` has less general versatility to give the additional feature to the DNN-model. Currently it has only the flag such as `use_speaker_embedding`  and we need to modify the class manually if more different features are need.

# New style
```yaml
data:
  # The key names can be used arbitrary
  input1:  
    path: feat1.scp
    type: hdf5
  input2: 
    path: feats2.scp
    type: ark
  text: 
    path: utt2tokenid
    type: csv
  lang: 
    path: utt2lang
  spk: 
    path: utt2spk
batch:
  sort: input1  # Sort utts in descending order of input1 length
  input1:
    shape: utt2feats1_shape  # (feat-Length, feat-dim)
    maxlen: 800
  text: 
    shape:  utt2text_shape  # (char-Length, N vocab)
    maxlen: 150
preprocess:
   input1: preprocess_feats.yaml
   text: preprocess_text.yaml
```

```bash
asr_train.py --train-data train.yaml 
```

```python
from espnet.utils.foo import Loader
d = yaml.load('train.yaml')
loader = Loader(...)
batches = make_batchset(d, ...)
for batch in batches:
    data = loader(batch)
    # data is dictionally
    input1_feat = data['input1']
    input2_feat = data['input2']
    text = data['text']
```
