### ISSUE TITLE
Default RNNLM rescoring works really badly even with dev set added to training set

### ISSUE THREAD

**Issue by ajd12342** [espnet/espnet#1745]
I am trying to use an sentencepiece token-based(with unigram BPE) RNNLM to rescore my CTC+attention ASR model (which also uses sentencepiece tokens) using the training script at the end of this text (it is very similar to stage 3 of the mini-an4/asr1 recipe) and using the configuration from the lm.yaml file at the end of this text. Trying the numbers in the comments of the yaml file(configurations for character based LMs) doesn't help either. Even after adding the dev set sentences to the training set, the performance does not improve. Using lmweight=0.0 gives the same performance as not using the LM model at all, as expected, and increasing the lmweight gradually worsens the WER and CER.

LM training script:
```bash
if [ ${stage} -le 3 ] && [ ${stop_stage} -ge 3 ]; then
    echo "stage 3: LM Preparation"

    if [ ${use_wordlm} = true ]; then
        lmdatadir=data/local/wordlm_train
        lmdict=${lmdatadir}/wordlist_${lm_vocabsize}.txt
        mkdir -p ${lmdatadir}
        cut -f 2- -d" " data/${train_set}/text > ${lmdatadir}/train.txt
        cut -f 2- -d" " data/${train_dev}/text >> ${lmdatadir}/train.txt
        cut -f 2- -d" " data/${train_dev}/text > ${lmdatadir}/valid.txt
        cut -f 2- -d" " data/${lm_test}/text > ${lmdatadir}/test.txt
        text2vocabulary.py -s ${lm_vocabsize} -o ${lmdict} ${lmdatadir}/train.txt
    else
        lmdatadir=data/local/lm_train
        lmdict=${dict}
        mkdir -p ${lmdatadir}

        text2token.py -s 1 -n 1 data/${train_set}/text \
            | cut -f 2- -d" " \
            | spm_encode --model=${bpemodel}.model --output_format=piece > ${lmdatadir}/train.txt
        text2token.py -s 1 -n 1 data/${train_dev}/text \
            | cut -f 2- -d" " \
            | spm_encode --model=${bpemodel}.model --output_format=piece >> ${lmdatadir}/valid.txt
        text2token.py -s 1 -n 1 data/${train_dev}/text \
            | cut -f 2- -d" " \
            | spm_encode --model=${bpemodel}.model --output_format=piece > ${lmdatadir}/valid.txt
        text2token.py -s 1 -n 1 data/${lm_test}/text \
            | cut -f 2- -d" " \
            | spm_encode --model=${bpemodel}.model --output_format=piece > ${lmdatadir}/test.txt
    fi

    ${cuda_cmd} --gpu ${ngpu} ${lmexpdir}/train.log \
        lm_train.py \
        --config ${lm_config} \
        --ngpu ${ngpu} \
        --backend ${backend} \
        --verbose 1 \
        --outdir ${lmexpdir} \
        --tensorboard-dir tensorboard/${lmexpname} \
        --train-label ${lmdatadir}/train.txt \
        --valid-label ${lmdatadir}/valid.txt \
        --test-label ${lmdatadir}/test.txt \
        --resume ${lm_resume} \
        --dict ${lmdict} \
        --dump-hdf5-path ${lmdatadir} \
        --seed ${seed}
fi
```
lm.yaml
```yaml
layer: 1         # 2 for character LMs
unit: 1000       # 650 for character LMs
opt: sgd          # adam for character LMs
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
batchsize: 300    # 1024 for character LMs
epoch: 80        # number of epochs
patience: 0
maxlen: 40        # 150 for character LMs
```
