### ISSUE TITLE
Hardcoded weights dict in espnet/asr/pytorch_backend/recog.py

### ISSUE THREAD

**Issue by Derek-Gong** [espnet/espnet#1818]
Hi, I was trying to develop my own scorer with ScorerInterface and found this issue. 
In recog.py, below line hardcoded weights dict, so scorers other than those shown in weights dict will not take effect. Because beam_search.py requires a scorer with a weight.
I guess this weights dict should be specified by users?

 scorers = model.scorers()
    scorers["lm"] = lm
    scorers["length_bonus"] = LengthBonus(len(train_args.char_list))
    weights = dict(
        decoder=1.0 - args.ctc_weight,
        ctc=args.ctc_weight,
        lm=args.lm_weight,
        length_bonus=args.penalty)

**Comment by sw005320** [comment]
@ShigekiKarita, do you have some comments about this?

**Comment by ShigekiKarita** [comment]
This is for compatibility with `--api v1`. Maybe it is time to stop to use `1.0 - args.ctc_weight`. IMO, the decoding config should be more flexible and extensible as well as our training config. We should stop hardcode for example, `ctc_window` or something model-specific or task-specific configs.

Maybe in espnet2, maybe we can use a YAML-based structured config.
```yaml
# decode.yml
builtin_scorers:
  decoder:
    weight: 0.5
  ctc:
    weight: 0.1
    window: 100
  lm:
    weight: 0.5
  length_bonus:
    weight: 0.1

custom_scorers:
  your_class1:  # arbitrary unique name
    weight: 1.0
    module: your_module:YourClass1 :  # arbitrary module in PYTHONPATH
    conf: "exp/your_model1/your_conf.yaml"
    state_dict: "exp/your_model1/your_state.pkl"
  your_class2:  # multiple custom scorers should be supported
    weight: 0.5
    module: your_module:YourClass2
    conf: "exp/your_model2/your_conf.yaml"
    state: "exp/your_model2/your_state.pkl"
  - ...
```
Thanks to [configargparse](https://github.com/bw2/ConfigArgParse), I expect that we can still tweak those nested args from bash like `--weights.decoder 0.0 --weights.ctc 1.0`

Then, we can load the custom models in recog.py:
```python
for scorer_name, scorer_def in args.custom_scorers.items():
  scorer_class = dynamic_import(scorer_def["module"])
  scorer_conf =yaml.load(scorer_def["conf"]) 
  scorer = scorer_class.build(**scorer_conf)
  state = torch.load(scorer_def["state"])
  scorer.load(scorer_state)
  # register args for BeamSearch
  scorers["custom_scorers/" + scorer_name] = scorer
  weights["custom_scorers/" + scorer_name] = scorer_def["weight"]
```
