### ISSUE TITLE
How do I get multi-speaker FastSpeech config in LibriTTS

### ISSUE THREAD

**Issue by xiuyayang** [espnet/espnet#1838]
Hi @kan-bayashi 
I had found your [PR](https://github.com/espnet/espnet/commit/04be9dc3c7c4e0d4778d05b4c3b1ff807229c093) multi_spk_fastspeech, but I not found in LibriTTS file config train_pytorch_fastspeech+spkemb.yaml.
Can you share this config.
Thanks.

**Comment by sw005320** [comment]
I think it is a good idea to share the config of multi-speaker FastSpeech.
@kan-bayashi, can you provide it?
Or if we have some issues (e.g., the performance is not good enough or it is not well trained), please share your experience.

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
I forgot about the multi-spk fastspeech, might be I implemented but did not conduct the experiment.
Maybe you can use the following configuration.
```yaml
# network architecture related
model-module: espnet.nets.pytorch_backend.e2e_tts_fastspeech:FeedForwardTransformer
adim: 384
aheads: 2
elayers: 6
eunits: 1536
dlayers: 6
dunits: 1536
duration-predictor-layers: 2
duration-predictor-chans: 256
duration-predictor-kernel-size: 3
positionwise-layer-type: conv1d
positionwise-conv-kernel-size: 3
postnet-layers: 5
postnet-filts: 5
postnet-chans: 256
use-batch-norm: True
use-scaled-pos-enc: True
encoder-normalize-before: False
decoder-normalize-before: False
encoder-concat-after: False
decoder-concat-after: False
reduction-factor: 2
use-speaker-embedding: true
spk-embed-integration-type: add

# minibatch related
# 64 * (343.1 * 80 + 60.049 * 43)
batch-sort-key: output # shuffle or input or output
batch-bins: 1921927    # avg batch-size * (mean_out * dim_out + mean_in * dim_in)
                       # 115 batches containing from 17 to 141 samples (avg 62 samples).

# training related
transformer-init: pytorch
transformer-warmup-steps: 4000
transformer-lr: 1.0
initial-encoder-alpha: 1.0
initial-decoder-alpha: 1.0
transformer-enc-dropout-rate: 0.1
transformer-enc-positional-dropout-rate: 0.1
transformer-enc-attn-dropout-rate: 0.1
transformer-dec-dropout-rate: 0.1
transformer-dec-positional-dropout-rate: 0.1
transformer-dec-attn-dropout-rate: 0.1
transformer-enc-dec-attn-dropout-rate: 0.1
postnet-dropout-rate: 0.5
duration-predictor-dropout-rate: 0.1
transfer-encoder-from-teacher: False
transferred-encoder-module: embed

# optimization related
opt: noam
accum-grad: 1
grad-clip: 1.0
weight-decay: 0.0
patience: 0
epochs: 1000  # 1000 epochs * 115 batches / 1 accum-grad = 115,000 iters
teacher-model: <your_teacher_model>

# other
save-interval-epoch: 50
```
