### ISSUE TITLE
question - tts retrain from model.acc.best 

### ISSUE THREAD

**Issue by marcosnetopires** [espnet/espnet#1889]
I saw here [https://github.com/espnet/espnet/issues/1591](url) that the option to load a model with the file model.acc.best for a TTS model is possible, but I'm having difficulties finding the option that should be added to the ./run.sh command to actually do this, to add the path to model.acc.best somehow.

**Comment by kan-bayashi** [comment]
You can add options in training yaml config.

e.g. 
```yaml
# case 1. if you want to load whole pretrained model
pretrained-model: /path/to/model.acc.best

# case 2. if you want to load subset of the pretrained model
# load only encoder
enc-init: /path/to/model.acc.best
enc-init-mods: "enc."
```
