### ISSUE TITLE
Tuning on Transformer RNN-T

### ISSUE THREAD

**Issue by zrsjta** [espnet/espnet#2606]
Hi! Thanks for this great project! :)
I am trying to tune a Transformer RNN-T on Aishell-1 dataset, following your config in `egs/vivos/asr1/conf/tuning/transducer/train_transformer_transducer.yaml` with some modification. I have extended the model into a much larger one, but encountered a over-fitting problem and a serious performance degradation compared with the LSTM version. Below is the details.

python:3.7.7
pytorch: 1.0.0
CUDA: 10.1
RNN-T binding: warp-transducer

All experiments are done with 4 Tesla M40 GPUs 

A typical config I use: 

```
batch-size: 30
maxlen-in: 800
maxlen-out: 150

criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
epochs: 40
patience: 0
accum-grad: 1
grad-clip: 5.0

transformer-lr: 1.0  # use lower lr for larger transformer
transformer-warmup-steps: 8000

etype: transformer
transformer-enc-input-layer: vgg2l
enc-block-arch:
        - type: transformer
          d_hidden: 768
          d_ff: 768
          heads: 12
          att-dropout-rate: 0.4
enc-block-repeat: 12

dtype: transformer
transformer-dec-input-layer: embed
dec-block-arch:
        - type: transformer
          d_hidden: 768
          d_ff: 768
          heads: 12
          dropout-rate: 0.1
          pos-dropout-rate: 0.1
          att-dropout-rate: 0.1
dec-block-repeat: 6

joint-dim: 768

rnnt-mode: 'rnnt' 
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
```

（1）When I use a LSTM version of RNN-T, with encoder "vgglstmp", 3 layer, 1024 hidden, and decoder "lstm", 1 layer, 1024 hidden, the test WERs are 7.8%/8.9% for dev/test set. with final training loss around 0.15 and valid loss around 5.13
（2）When I use the transformer version of RNN-T, with the config above, though the training loss could reach the same level(around 0.15), the valid loss is around 7, which is much worse than the LSTM version. Also, the valid loss would grow higher or fluctuate even during the first half of training without getting lower any further. So I assume this is an over-fitting problem 
（3）I find SpecAugment is much helpful to alleviate this problem: similar valid loss with that of LSTM version. But I want to bypass the use of that trick.
（4） I have also tried to: A. use a much smaller encoder-decoder layer number and hidden size (8 encoder, 4 decoder and 512 hidden); B. change the att-dropout-rate of encoder from 0.4 to 0.1; C. Change the d_ff size to 2048; D. tuning the learning rate. All of these attempts leads to similar or even worse results on dev_loss. 
（5）For those with poor valid_loss, I have not do the decoding stage to check the final WER but those CERs can hardly be better than that of LSTM version, I guess. I would do the decoding and report here later if needed.
（6）All experiments are done with 4 GPUs. the total batch size is 120 so I disable the accum-grad setting.

It seems that the config above consumes around 100M parameter budget but is still poor in performance. How should I tune a good config? Thanks for anyone who can help!

regards!
