### ISSUE TITLE
How to use pretrained wav2vec encoder for finetuning transformer based ASR?

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#3229]
Hi

I am trying to use a pretrained wav2vec model present in my local machine for asr training (no existing w2v_url). I am not sure how to change the config yaml file.

For example, this is default encoder conf in train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer.yaml right now

```yml
encoder_conf:    
    output_size: 1024    
    normalize_before: false    
    freeze_finetune_updates: 100000    
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h_new.pt    
    w2v_dir_path: ./downloads/wav2vec_pretrained_models
```

my pretrained model file is checkpoint_best.pt and it is located in ./pretrained_wav2vec_model/

**Comment by sw005320** [comment]
@simpleoier, could you answer it?

**Comment by simpleoier** [comment]
Hi @nellorebhanuteja . I actually didn't well considered the local checkpoint. But it is a good point and relatively easy to do. At this [line](https://github.com/espnet/espnet/blob/fe551ff9370dbb95507d74701c139743b180fa59/espnet2/asr/encoder/wav2vec2_encoder.py#L57)

**Comment by nellorebhanuteja** [comment]
Hi @simpleoier 

I have tried your suggestion.  download_w2v function does return correct model path with that trick.

However, I am getting a new error


For example, if I provide a downloadable URL

```python
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 100000
    w2v_url: https://storage.googleapis.com/vakyaansh-open-models/hindi/pretrained/hindi_pretrained_4kh.pt
    w2v_dir_path: ./pretrained_wav2vec_model/
```

it works. But if I provide dummy URL 
```python
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 100000
    w2v_url: https://dummyurl.com/hindi_pretrained_4kh.pt
    w2v_dir_path: ./pretrained_wav2vec_model/
```

I get the following error
```text
File "/data0/espnet/espnet2/asr/encoder/wav2vec2_encoder.py", line 64, in __init__
    models, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task(
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 286, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 234, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
```


Essentially, for the same model, downloadable URL works and downloaded file doesn't work.

**Comment by simpleoier** [comment]
@nellorebhanuteja It's good to know that `download_w2v function does return correct model path with that trick.`.  I guess the reason probably is  that the `dictionary` file. When downloading a model from URL, it  also download the [dict](https://github.com/espnet/espnet/blob/fe551ff9370dbb95507d74701c139743b180fa59/espnet2/asr/encoder/wav2vec2_encoder.py#L160). I think you can try to put the dict file along with the model at `w2v_dir_path`.

**Comment by nellorebhanuteja** [comment]
@simpleoier manually copied dict.ltr.txt from "https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt" to ./pretrained_wav2vec_model. Still the same error.

Did you try using a manually downloaded model from your end?

**Comment by simpleoier** [comment]
@nellorebhanuteja Yes, I tried it and it works. 
Here is the output log, showing that the model is loaded.
```
(asr:360) INFO: Vocabulary size: 5000
(filelock:274) INFO: Lock 46999932003984 acquired on ./downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning/wav2vec_small_960h.pt.lock
INFO: Wav2Vec model ./downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning/wav2vec_small_960h.pt already exists.
INFO: Lock 46999932003984 released on ./downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning/wav2vec_small_960h.pt.lock
(wav2vec2_encoder:145) INFO: Pretrained Wav2Vec model parameters reloaded!
(abs_task:1090) INFO: Setting encoder.encoders.mask_emb.requires_grad = False
...
```
Here is the config
```
encoder: wav2vec2
encoder_conf:
    output_size: 512
    normalize_before: true
    freeze_finetune_updates: 1000000
    w2v_url: https://downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning/wav2vec_small_960h.pt
    w2v_dir_path: ./downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning
```
Here is the stuff in download dir path
```
$ ls downloads_try/wav2vec_pretrained_models/wav2vec2.0_base_960h_finetuning 
dict.ltr.txt  wav2vec_small_960h.pt  wav2vec_small_960h.pt.lock
```

> AttributeError: 'NoneType' object has no attribute 'data'

The  error information you  provided is very limited. Can you make sure if the model file is correctly passed to fairseq model loader? What exactly is the `NoneType` referring to?
