### ISSUE TITLE
[Usage help] joint TTS training

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#3536]
Hello @kan-bayashi I can see gan_tts task now work with joint TTS training but wondering if you have example for specify pretrained models, switching vocoder impl and expected training time difference.

**Comment by kan-bayashi** [comment]
Now I'm testing several settings
- Joint training from scratch
- Joint fine-tuning with the pretrained text2mel and vocoder

I will update the README.

**Comment by kan-bayashi** [comment]
Example with https://github.com/espnet/espnet/blob/master/egs2/ljspeech/tts1/conf/tuning/train_joint_conformer_fastspeech2_hifigan.yaml

```bash
# Assume that ready to run fastspeech2 training
$ cd egs2/ljspeech/tts1
$ ./run.sh \
    --ngpu 4 \
    --stage 6 \
    --tts_task gan_tts \
    --feats_extract fbank \
    --feats_normalize global_mvn \
    --teacher_dumpdir /path/to/teacher_dumpdir \
    --tts_stats_dir /path/to/stats_dir \
    --train_config ./conf/tuning/train_joint_conformer_fastspeech2_hifigan.yaml
```

**Comment by gafsd** [comment]
How to specify pretrain? I am still work on small dataset so wonder if it would converge better with pretrain. 
Is it faster to train like this? Or better quality?

**Comment by kan-bayashi** [comment]
I'm still in the investigation with ljspeech.
From current comparison:
1. Separately trained fastspeech2 + hifigan
	- Not good since hifigan produce metallic sound due to the mismatch of feature.
2. Fastspeech2 + hifigan finetuned with GTA mel
	- On-going but it can reduce the metallic sound.
3. Joint training of fastspeech2 + hifigan from scratch
	- Slow convergence but sounds good, no metallic sound
4. Fine-tuning of fastspeech 2 + hifigan 
	- Pretrained fs2 + pretrained hifigan G + initialized hifigan D
	- Slow convergence but sounds good
	- Using pretrained hifigan D is unstable, fs2 is broken in the early stage.

To load the pretrained model, you can use `--init_param` option.

```yaml
# This EXPERIMENTAL configuration is for ESPnet2 to finetune
# Conformer FastSpeech2 + HiFiGAN vocoder jointly. To run
# this config, you need to specify "--tts_task gan_tts"
# option for tts.sh at least and use 22050 hz audio as the
# training data (mainly tested on LJspeech).
# This configuration tested on 4 GPUs with 12GB GPU memory.
# It takes around 2 weeks to finish the training but 100k
# iters model should generate reasonable results.

##########################################################
#                  TTS MODEL SETTING                     #
##########################################################
tts: joint_text2wav
tts_conf:
    # copied from pretrained model's config.yaml
    text2mel_type: fastspeech2
    text2mel_params:
        adim: 384
        aheads: 2
        conformer_activation_type: swish
        conformer_dec_kernel_size: 31
        conformer_enc_kernel_size: 7
        conformer_pos_enc_layer_type: rel_pos
        conformer_self_attn_layer_type: rel_selfattn
        decoder_normalize_before: false
        decoder_type: conformer
        dlayers: 4
        dunits: 1536
        duration_predictor_chans: 256
        duration_predictor_kernel_size: 3
        duration_predictor_layers: 2
        elayers: 4
        encoder_normalize_before: false
        encoder_type: conformer
        energy_embed_dropout: 0.0
        energy_embed_kernel_size: 1
        energy_predictor_chans: 256
        energy_predictor_dropout: 0.5
        energy_predictor_kernel_size: 3
        energy_predictor_layers: 2
        eunits: 1536
        init_type: xavier_uniform
        pitch_embed_dropout: 0.0
        pitch_embed_kernel_size: 1
        pitch_predictor_chans: 256
        pitch_predictor_dropout: 0.5
        pitch_predictor_kernel_size: 5
        pitch_predictor_layers: 5
        positionwise_conv_kernel_size: 3
        positionwise_layer_type: conv1d
        postnet_chans: 256
        postnet_filts: 5
        postnet_layers: 5
        reduction_factor: 1
        stop_gradient_from_energy_predictor: false
        stop_gradient_from_pitch_predictor: true
        transformer_dec_attn_dropout_rate: 0.2
        transformer_dec_dropout_rate: 0.2
        transformer_dec_positional_dropout_rate: 0.2
        transformer_enc_attn_dropout_rate: 0.2
        transformer_enc_dropout_rate: 0.2
        transformer_enc_positional_dropout_rate: 0.2
        use_cnn_in_conformer: true
        use_macaron_style_in_conformer: true
        use_masking: true

    # copied from pretrained vocoder's config.yaml
    vocoder_type: hifigan_generator
    vocoder_params:
        bias: true
        channels: 512
        in_channels: 80
        kernel_size: 7
        nonlinear_activation: LeakyReLU
        nonlinear_activation_params:
            negative_slope: 0.1
        out_channels: 1
        resblock_dilations:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        resblock_kernel_sizes:
        - 3
        - 7
        - 11
        upsample_kernel_sizes:
        - 16
        - 16
        - 4
        - 4
        upsample_scales:
        - 8
        - 8
        - 2
        - 2
        use_additional_convs: true
        use_weight_norm: true

    # discriminator related
    discriminator_type: hifigan_multi_scale_multi_period_discriminator
    discriminator_params:
        scales: 1
        scale_downsample_pooling: "AvgPool1d"
        scale_downsample_pooling_params:
            kernel_size: 4
            stride: 2
            padding: 2
        scale_discriminator_params:
            in_channels: 1
            out_channels: 1
            kernel_sizes: [15, 41, 5, 3]
            channels: 128
            max_downsample_channels: 1024
            max_groups: 16
            bias: True
            downsample_scales: [2, 2, 4, 4, 1]
            nonlinear_activation: "LeakyReLU"
            nonlinear_activation_params:
                negative_slope: 0.1
            use_weight_norm: True
            use_spectral_norm: False
        follow_official_norm: False
        periods: [2, 3, 5, 7, 11]
        period_discriminator_params:
            in_channels: 1
            out_channels: 1
            kernel_sizes: [5, 3]
            channels: 32
            downsample_scales: [3, 3, 3, 3, 1]
            max_downsample_channels: 1024
            bias: True
            nonlinear_activation: "LeakyReLU"
            nonlinear_activation_params:
                negative_slope: 0.1
            use_weight_norm: True
            use_spectral_norm: False

    # loss function related
    generator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    discriminator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    use_feat_match_loss: true            # whether to use feat match loss
    feat_match_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        average_by_layers: false         # whether to average loss value by #layers of each discriminator
        include_final_outputs: true      # whether to include final outputs for loss calculation
    use_mel_loss: true     # whether to use mel-spectrogram loss
    mel_loss_params:
        fs: 22050          # must be the same as the training data
        n_fft: 1024        # fft points
        hop_length: 256    # hop size
        win_length: null   # window length
        window: hann       # window type
        n_mels: 80         # number of Mel basis
        fmin: 0            # minimum frequency for Mel basis
        fmax: null         # maximum frequency for Mel basis
        log_base: null     # null represent natural log
    lambda_text2mel: 1.0   # loss scaling coefficient for text2mel loss
    lambda_adv: 1.0        # loss scaling coefficient for adversarial loss
    lambda_mel: 45.0       # loss scaling coefficient for Mel loss
    lambda_feat_match: 2.0 # loss scaling coefficient for feat match loss

    # others
    sampling_rate: 22050          # needed in the inference for saving wav
    segment_size: 32              # segment size for random windowed discriminator
    cache_generator_outputs: true # whether to cache generator outputs in the training

# extra module for additional inputs
pitch_extract: dio           # pitch extractor type
pitch_extract_conf:
    reduction_factor: 1
pitch_normalize: global_mvn  # normalizer for the pitch feature
energy_extract: energy       # energy extractor type
energy_extract_conf:
    reduction_factor: 1
energy_normalize: global_mvn # normalizer for the energy feature

# initialization
init_param:
- exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth:tts:tts.generator.text2mel
- exp/ljspeech_hifigan.v1/generator.pth::tts.generator.vocoder

##########################################################
#            OPTIMIZER & SCHEDULER SETTING               #
##########################################################
# optimizer setting for generator
optim: adamw
optim_conf:
    lr: 2.0e-4
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
# optimizer setting for discriminator
optim2: adamw
optim2_conf:
    lr: 2.0e-4
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true # whether to start updating generator first

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 500  # number of iterations per epoch
max_epoch: 2000           # number of epochs
accum_grad: 1             # gradient accumulation
batch_bins: 5000000       # batch bins (feats_type=raw)
batch_type: numel         # how to make batch
grad_clip: -1             # gradient clipping norm
grad_noise: false         # whether to use gradient noise injection
sort_in_batch: descending # how to sort data in making batch
sort_batch: descending    # how to sort created batches
num_workers: 4            # number of workers of data loader
use_amp: false            # whether to use pytorch amp
log_interval: 10          # log interval in iterations
keep_nbest_models: 5      # number of models to keep
num_att_plot: 3           # number of attention figures to be saved in every check
seed: 777                 # random seed number
patience: null            # patience for early stopping
unused_parameters: true   # needed for multi gpu case
best_model_criterion:     # criterion to save the best models
-   - train
    - total_count
    - max
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
```

The vocoder ckpt can be converted like this.
```python
# convert parallel_wavegan ckpt to be loadable in espnet2
[ins] In [1]: import torch
[ins] In [2]: d = torch.load("./exp/ljspeech_hifigan.v1/checkpoint-2500000steps.pkl")
[ins] In [4]: torch.save(d["model"]["generator"], "generator.pth")
[ins] In [5]: torch.save(d["model"]["discriminator"], "discriminator.pth")
```

**Comment by gafsd** [comment]
Wow it's exciting to see some progress. I can run some experiemnt on small data (1-3 hours) couple datasets. Do you think finetuning would be better for this? And it would work with `--train_args "--init_param generator.pth --init_param fs2.pth"`?

**Comment by gafsd** [comment]
Ok I will try fine tune with hifigan G + pretrain fs2. I note we still use legacy conformer - is that intended?

**Comment by kan-bayashi** [comment]
> Ok I will try fine tune with hifigan G + pretrain fs2. We still use legacy conformer - is that intended?

It is no problem.
Also, this config seems working with the pretrained D.
```yaml
# This EXPERIMENTAL configuration is for ESPnet2 to finetune
# Conformer FastSpeech2 + HiFiGAN vocoder jointly. To run
# this config, you need to specify "--tts_task gan_tts"
# option for tts.sh at least and use 22050 hz audio as the
# training data (mainly tested on LJspeech).
# This configuration tested on 4 GPUs with 12GB GPU memory.
# It takes around 2 weeks to finish the training but 100k
# iters model should generate reasonable results.

##########################################################
#                  TTS MODEL SETTING                     #
##########################################################
tts: joint_text2wav
tts_conf:
    # copied from pretrained model's config.yaml
    text2mel_type: fastspeech2
    text2mel_params:
        adim: 384
        aheads: 2
        conformer_activation_type: swish
        conformer_dec_kernel_size: 31
        conformer_enc_kernel_size: 7
        conformer_pos_enc_layer_type: rel_pos
        conformer_self_attn_layer_type: rel_selfattn
        decoder_normalize_before: false
        decoder_type: conformer
        dlayers: 4
        dunits: 1536
        duration_predictor_chans: 256
        duration_predictor_kernel_size: 3
        duration_predictor_layers: 2
        elayers: 4
        encoder_normalize_before: false
        encoder_type: conformer
        energy_embed_dropout: 0.0
        energy_embed_kernel_size: 1
        energy_predictor_chans: 256
        energy_predictor_dropout: 0.5
        energy_predictor_kernel_size: 3
        energy_predictor_layers: 2
        eunits: 1536
        init_type: xavier_uniform
        pitch_embed_dropout: 0.0
        pitch_embed_kernel_size: 1
        pitch_predictor_chans: 256
        pitch_predictor_dropout: 0.5
        pitch_predictor_kernel_size: 5
        pitch_predictor_layers: 5
        positionwise_conv_kernel_size: 3
        positionwise_layer_type: conv1d
        postnet_chans: 256
        postnet_filts: 5
        postnet_layers: 5
        reduction_factor: 1
        stop_gradient_from_energy_predictor: false
        stop_gradient_from_pitch_predictor: true
        transformer_dec_attn_dropout_rate: 0.2
        transformer_dec_dropout_rate: 0.2
        transformer_dec_positional_dropout_rate: 0.2
        transformer_enc_attn_dropout_rate: 0.2
        transformer_enc_dropout_rate: 0.2
        transformer_enc_positional_dropout_rate: 0.2
        use_cnn_in_conformer: true
        use_macaron_style_in_conformer: true
        use_masking: true

    # copied from pretrained vocoder's config.yaml
    vocoder_type: hifigan_generator
    vocoder_params:
        bias: true
        channels: 512
        in_channels: 80
        kernel_size: 7
        nonlinear_activation: LeakyReLU
        nonlinear_activation_params:
            negative_slope: 0.1
        out_channels: 1
        resblock_dilations:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        resblock_kernel_sizes:
        - 3
        - 7
        - 11
        upsample_kernel_sizes:
        - 16
        - 16
        - 4
        - 4
        upsample_scales:
        - 8
        - 8
        - 2
        - 2
        use_additional_convs: true
        use_weight_norm: true

    # copied from pretrained vocoder's config.yaml
    discriminator_type: hifigan_multi_scale_multi_period_discriminator
    discriminator_params:
        follow_official_norm: true
        period_discriminator_params:
            bias: true
            channels: 32
            downsample_scales:
            - 3
            - 3
            - 3
            - 3
            - 1
            in_channels: 1
            kernel_sizes:
            - 5
            - 3
            max_downsample_channels: 1024
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
            use_spectral_norm: false
            use_weight_norm: true
        periods:
        - 2
        - 3
        - 5
        - 7
        - 11
        scale_discriminator_params:
            bias: true
            channels: 128
            downsample_scales:
            - 4
            - 4
            - 4
            - 4
            - 1
            in_channels: 1
            kernel_sizes:
            - 15
            - 41
            - 5
            - 3
            max_downsample_channels: 1024
            max_groups: 16
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
        scale_downsample_pooling: AvgPool1d
        scale_downsample_pooling_params:
            kernel_size: 4
            padding: 2
            stride: 2
        scales: 3

    # loss function related
    generator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    discriminator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    use_feat_match_loss: true            # whether to use feat match loss
    feat_match_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        average_by_layers: false         # whether to average loss value by #layers of each discriminator
        include_final_outputs: true      # whether to include final outputs for loss calculation
    use_mel_loss: true     # whether to use mel-spectrogram loss
    mel_loss_params:
        fs: 22050          # must be the same as the training data
        n_fft: 1024        # fft points
        hop_length: 256    # hop size
        win_length: null   # window length
        window: hann       # window type
        n_mels: 80         # number of Mel basis
        fmin: 0            # minimum frequency for Mel basis
        fmax: null         # maximum frequency for Mel basis
        log_base: null     # null represent natural log
    lambda_text2mel: 1.0   # loss scaling coefficient for text2mel loss
    lambda_adv: 1.0        # loss scaling coefficient for adversarial loss
    lambda_mel: 45.0       # loss scaling coefficient for Mel loss
    lambda_feat_match: 2.0 # loss scaling coefficient for feat match loss

    # others
    sampling_rate: 22050          # needed in the inference for saving wav
    segment_size: 32              # segment size for random windowed discriminator
    cache_generator_outputs: true # whether to cache generator outputs in the training

# extra module for additional inputs
pitch_extract: dio           # pitch extractor type
pitch_extract_conf:
    reduction_factor: 1
pitch_normalize: global_mvn  # normalizer for the pitch feature
energy_extract: energy       # energy extractor type
energy_extract_conf:
    reduction_factor: 1
energy_normalize: global_mvn # normalizer for the energy feature

# initialization
init_param:
- exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth:tts:tts.generator.text2mel
- exp/ljspeech_hifigan.v1/generator.pth::tts.generator.vocoder
- exp/ljspeech_hifigan.v1/discriminator.pth::tts.discriminator

##########################################################
#            OPTIMIZER & SCHEDULER SETTING               #
##########################################################
# optimizer setting for generator
optim: adam
optim_conf:
    lr: 1.25e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
# optimizer setting for discriminator
optim2: adam
optim2_conf:
    lr: 1.25e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true # whether to start updating generator first

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 500  # number of iterations per epoch
max_epoch: 200            # number of epochs
accum_grad: 1             # gradient accumulation
batch_bins: 5000000       # batch bins (feats_type=raw)
batch_type: numel         # how to make batch
grad_clip: -1             # gradient clipping norm
grad_noise: false         # whether to use gradient noise injection
sort_in_batch: descending # how to sort data in making batch
sort_batch: descending    # how to sort created batches
num_workers: 4            # number of workers of data loader
use_amp: false            # whether to use pytorch amp
log_interval: 10          # log interval in iterations
keep_nbest_models: 5      # number of models to keep
num_att_plot: 3           # number of attention figures to be saved in every check
seed: 777                 # random seed number
patience: null            # patience for early stopping
unused_parameters: true   # needed for multi gpu case
best_model_criterion:     # criterion to save the best models
-   - valid
    - text2mel_loss
    - min
-   - train
    - text2mel_loss
    - min
-   - valid
    - loss
    - min
-   - train
    - loss
    - min

**Comment by gafsd** [comment]
I trained model fs2 pretrain + hifigan G pretrain + fresh hifigan D for 24 hours and result was very encouraging! Pitch is sound really good much better than finetune separately but metallic voice is quite bad (worse than melgan-pwg finetuning). I will switch to use pretrain hifigan D and see if it improve tomorrow.

**Comment by gafsd** [comment]
Sadly using pretrain config above makes espnet hang again after a few batches. Not sure if my setup but it hang everytime and I can't complete epoch.

**Comment by gafsd** [comment]
I am having a lot of trouble, it is hang every time and GPU utilisation drops to 0% during. How can I debug ?

**Comment by kan-bayashi** [comment]
Please check `*_time` in `train.log`, which help to find the bottleneck.

**Comment by gafsd** [comment]
I looked into it and I think it is hanging on iter(DataLoader) in reporter.py#measure_iter_time. I tried with num_workers = 0 and it hang on sleep and with num_workers > 0 it hang on iter() call. I look for other bug report but not found any solution. Using Ubuntu 18.04 with python 3.7

**Comment by gafsd** [comment]
I am looking into it more and I think it is very strange issue I am having. It hang here every time I run it: https://github.com/espnet/espnet/blob/master/espnet2/train/gan_trainer.py#L261
It hangs after a few iters and always on discriminator optimizer (Adam) idx=1 grad_norm=None no scaler. I will keep looking but do you have any idea?

Also I will check VITS finetune too and compare if I fix this issue

**Comment by kan-bayashi** [comment]
@gafsd Thank you for your investigation.
I'm wondering your issue is only happened in the case of gan training or not.
e.g., 
> - I tried with num_workers = 0 and it hang on espnet2/bin/launch.py:359 (never complete) and with num_workers > 0 it hang on iter() call. I look for other bug report but not found any solution. Using Ubuntu 18.04 with python 3.7

If you fill out the bug report template, I may be able to say something more.

**Comment by gafsd** [comment]
I check fs2 pretrain + hifigan G + D pretrain trained 39epochs and the metallic noise is reduced a lot but still present. Is there anything else I can adjust to reduce or more training? And have you tried multispeaker finetune? Overall I am impressed as the result is much better than finetuning separately. I wonder if using PWG discrim or generator would be good too.

Next I will try on another dataset. Do you get good result with VITS finetune? I can try that too.

**Comment by kan-bayashi** [comment]
Thanks for sharing your experiments.
Multi-speaker has not yet tried but VITS finetuning works well (easy and good quality in Japanese dataset).
You can find examples in `egs2/jvs/tts1`.

**Comment by gafsd** [comment]
Ok I've trained 39epoch of VITS and it sound good but have some prosody issue (chopping of syllable). I am quite impress with both actually so it is tricky but I think VITS have better smoother wave output (no metallic noise) but worse prosody and sometimes mispronounce, fs2+hifigan have good prosody but metallic noise in some sentence and more monotone. 

Couple questions:
Any suggestions you have for reduce metallic noise? 
Is it better to use other vocoder with joint training? 
I find that VITS mispronounce at end of sentence a lot, is this known issue or due to VITS itself?
And for multispeaker how to train and run? I can't see libritts/vctk yet to finetune. Do you think if I add some speaker to vctk data it will generalise?

**Comment by kan-bayashi** [comment]
> Any suggestions you have for reduce metallic noise?
> Is it better to use other vocoder with joint training?

From my experiments, the vocoders without noise inputs (e.g., MelGAN / HiFiGAN) tend to cause metallic noise when the inputs are mismatched. The vocoders like PWG and StyleMelGAN are more robust to the mismatch and produce less noise. So joint training with Style MelGAN might be interesting (I've not yet tried). And joint training from scratch seems better than joint fine-tuning.

> I find that VITS mispronounce at end of sentence a lot, is this known issue or due to VITS itself?

In the early stage of VITS training, the pronunciation is fragile but long iteration improve it.

> And for multispeaker how to train and run? I can't see libritts/vctk yet to finetune. Do you think if I add some speaker to vctk data it will generalise?

I have not yet tried. It might be promising.

**Comment by gafsd** [comment]
Hmm you mean joint training with pretrain fs2 but no pretrain vocoder? I only have small datasets so might be hard to train fs2 scratch. I can try with fresh StyleMelGAN if I have config (I think some changes need made from ParallelWaveGAN cfg).

**Comment by kan-bayashi** [comment]
> you mean joint training with pretrain fs2 but no pretrain vocoder?

No, train the initialized fs2 + hifigan g & d from scratch.
I updated the results #3578, finetuning form this model might be interesting?

> I think some changes need made from ParallelWaveGAN cfg.

You can copy `generator_params` and `discriminator_params` in PWG pretrained model and copied to `vocoder_params` and `discriminator_params` in espnet2 finetuning config.

**Comment by gafsd** [comment]
Ok I try finetune from all three pretrain today. I think initial fs2 hard to train from scratch on small single speaker data... I can maybe try though. And then StyleMelGAN

**Comment by gafsd** [comment]
I try with pretrain all three finetuned and it sound worse actually than pretrain fs2 + hifigan generator (although training only at 18epoch so far); is this init_param wrong?
```
init_param:
- pretrain/tts_finetune_joint_conformer_fastspeech2_hifigan.v8_raw_phn_tacotron_g2p_en_no_space/train.total_count.ave_5best.pth:tts:tts
```

**Comment by kan-bayashi** [comment]
> I try with pretrain all three finetuned and it sound worse actually than pretrain fs2 + hifigan G+D (although training only at 18epoch so far); is this init_param wrong?

It seems fine, the optimizer setting may be slightly different.
Please check carefully.

For style melgan, you need to use `segment_size = prod(noise_upsample_scales)`.

**Comment by gafsd** [comment]
I notice you train vctk vits. How do you find results? Compare to single speaker?

**Comment by kan-bayashi** [comment]
Compared with a single speaker, the quality is almost the same (not yet compared strictly). But in terms of multi-speaker model, it is much better than FS2 + x-vector approach.

**Comment by gafsd** [comment]
I try style_melgan finetune but result is very bad, (complete corrupt audio) not sure if my config is wrong
```
    # copied from pretrained vocoder's config.yaml
    vocoder_type: style_melgan_generator
    vocoder_params:
        in_channels: 128
        aux_channels: 80
        channels: 64
        out_channels: 1
        kernel_size: 9
        dilation: 2
        bias: True
        noise_upsample_scales: [11, 2, 2, 2]
        noise_upsample_activation: "LeakyReLU"
        noise_upsample_activation_params:
            negative_slope: 0.2
        upsample_scales: [2, 2, 2, 2, 2, 2, 2, 2, 1]
        upsample_mode: "nearest"
        gated_function: "softmax"
        use_weight_norm: True

    # copied from pretrained vocoder's config.yaml
    discriminator_type: style_melgan_discriminator
    discriminator_params:
        repeats: 4
        window_sizes: [512, 1024, 2048, 4096]
        pqmf_params:
            - [1, None, None, None]
            - [2, 62, 0.26700, 9.0]
            - [4, 62, 0.14200, 9.0]
            - [8, 62, 0.07949, 9.0]
        discriminator_params:
            out_channels: 1
            kernel_sizes: [5, 3]
            channels: 16
            max_downsample_channels: 512
            bias: True
            downsample_scales: [4, 4, 4, 1]
            nonlinear_activation: "LeakyReLU"
            nonlinear_activation_params:
                negative_slope: 0.2
        use_weight_norm: True
segment_size: 88
 generator_adv_loss_params:
      average_by_discriminators: false # whether to average loss value by #discriminators
      loss_type: mse                   # loss type, "mse" or "hinge"
  discriminator_adv_loss_params:
      average_by_discriminators: false # whether to average loss value by #discriminators
      loss_type: mse                   # loss type, "mse" or "hinge"
  use_feat_match_loss: true            # whether to use feat match loss
  feat_match_loss_params:
      average_by_discriminators: false # whether to average loss value by #discriminators
      average_by_layers: false         # whether to average loss value by #layers of each discriminator
      include_final_outputs: true      # whether to include final outputs for loss calculation
  use_mel_loss: true     # whether to use mel-spectrogram loss
  mel_loss_params:
      fs: 22050          # must be the same as the training data
      n_fft: 1024        # fft points
      hop_length: 256    # hop size
      win_length: null   # window length
      window: hann       # window type
      n_mels: 80         # number of Mel basis
      fmin: 0            # minimum frequency for Mel basis
      fmax: null         # maximum frequency for Mel basis
      log_base: null     # null represent natural log
  lambda_text2mel: 1.0   # loss scaling coefficient for text2mel loss
  lambda_adv: 1.0        # loss scaling coefficient for adversarial loss
  lambda_mel: 1.0       # loss scaling coefficient for Mel loss
  lambda_feat_match: 2.0 # loss scaling coefficient for feat match loss
```

**Comment by kan-bayashi** [comment]
Optimizer setting is very sensitive.
How was it?

**Comment by gafsd** [comment]
```
optim: adamw
optim_conf:
    lr: 2.0e-4
    betas: [0.7, 0.99]
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
# optimizer setting for discriminator
optim2: adamw
optim2_conf:
    lr: 2.0e-4
    betas: [0.8, 0.99]
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true # whether to start updating generator first
```
