### ISSUE TITLE
Hang when training

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#3562]
**Describe the bug**
Sometimes in training espnet hang while iterating

**Basic environments:**
 - OS information: `Linux 5.10.43 #1 SMP Ubuntu Bionic Beaver 18.04.5 x86_64`
 - python version: Python 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
 - espnet version: main
 - Git hash 65e1d4627ba84401fb68176b6aace2a9e321a79c
 - pytorch 1.9.0

**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Libc version: glibc-2.10

Python version: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.10.43
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.06
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2 
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py37h27cfd23_1
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.1            py37ha9443f7_2
[conda] mypy_extensions           0.4.3                    py37_0
[conda] numpy                     1.20.1           py37h93e21f0_0
[conda] numpy-base                1.20.1           py37h7d8b39e_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.9.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torchaudio                0.9.0                      py37    pytorch
[conda] torchvision               0.10.0               py37_cu111    pytorch
```

**Task information:**
 - Task: TTS
 - Recipe: multiple previously but I only have debug statement for ljspeech/gan training
 - ESPNet 2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs2/ljspeech/tts`
2. execute joint gan training task
3. exp log will stop update after some iters (random amount)

I add debug output and it freeze on optimizer.step() call after unknown iters
**Error logs**
```
# python3 -m espnet2.bin.gan_tts_train --use_preprocessor true --token_type phn --token_list dump/token_list/phn_tacotron_g2p_en_no_space/tokens.txt --non_linguistic_symbols none --cleaner tacotron --g2p g2p_en_no_space --normalize global_mvn --resume true --fold_length 150 --fold_length 204800 --output_dir exp/tts_joint_fs2_hifigan_discrim --config conf/tuning/train_joint_conformer_fastspeech2_hifigan_discrim.yaml --train_data_path_and_name_and_type dump/raw/tr_no_dev/text,text,text --train_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/tr_no_dev/durations,durations,text_int --train_shape_file exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/text_shape.phn --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/dev/durations,durations,text_int --valid_shape_file exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/valid/text_shape.phn --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --train_data_path_and_name_and_type dump/raw/tr_no_dev/wav.scp,speech,sound --train_shape_file exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/speech_shape --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_shape_file exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/valid/speech_shape --train_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/collect_feats/pitch.scp,pitch,npy --valid_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/valid/collect_feats/pitch.scp,pitch,npy --train_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/collect_feats/energy.scp,energy,npy --valid_data_path_and_name_and_type exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/valid/collect_feats/energy.scp,energy,npy --pitch_extract_conf fs=22050 --pitch_extract_conf n_fft=1024 --pitch_extract_conf hop_length=256 --pitch_extract_conf f0max=400 --pitch_extract_conf f0min=80 --pitch_normalize_conf stats_file=exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/pitch_stats.npz --energy_extract_conf fs=22050 --energy_extract_conf n_fft=1024 --energy_extract_conf hop_length=256 --energy_extract_conf win_length=null --energy_normalize_conf stats_file=exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/energy_stats.npz --normalize_conf stats_file=exp/tts_teacher/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/feats_stats.npz --ngpu 1 --multiprocessing_distributed True 

2021-09-05 12:53:58,946 (trainer:274) INFO: 1/2000epoch started 
2021-09-05 12:54:09,654 (gan_trainer:261) INFO: pre_optim None <class 'torch.optim.adam.Adam'> 0 1
2021-09-05 12:54:09,655 (gan_trainer:271) INFO: !!! pre_optim <class 'torch.optim.adam.Adam'>
2021-09-05 12:54:09,656 (gan_trainer:261) INFO: pre_optim None <class 'torch.optim.adam.Adam'> 1 1
2021-09-05 12:54:09,932 (gan_trainer:261) INFO: pre_optim None <class 'torch.optim.adam.Adam'> 0 1
2021-09-05 12:54:09,933 (gan_trainer:261) INFO: pre_optim None <class 'torch.optim.adam.Adam'> 1 1
2021-09-05 12:54:09,933 (gan_trainer:271) INFO: !!! pre_optim <class 'torch.optim.adam.Adam'>

with following code change
with reporter.measure_time(f"{turn}_optim_step_time"): 
    for iopt, (optimizer, scheduler) in enumerate(
        zip(optimizers, schedulers)
    ):
        logging.info (f'pre_optim {scaler} {type(optimizer)} {iopt} {optim_idx}')
        if optim_idx is not None and iopt != optim_idx:
            continue
        if scaler is not None:
            # scaler.step() first unscales the gradients of
            # the optimizer's assigned params.
            scaler.step(optimizer)
            # Updates the scale for next iteration.
            scaler.update()
        else:
            logging.info (f'!!! pre_optim {type(optimizer)}')
            optimizer.step()
        logging.info (f'pre_schedule {scheduler}')
        if isinstance(scheduler, AbsBatchStepScheduler):
            scheduler.step() 
```

**Comment by kan-bayashi** [comment]
Thank you for your report.
Could you also attach the config (`conf/tuning/train_joint_conformer_fastspeech2_hifigan_discrim.yaml`)?

> logging.info (f'pre_schedule {scheduler}')

Did this message appear?

**Comment by gafsd** [comment]
```
# This EXPERIMENTAL configuration is for ESPnet2 to finetune
# Conformer FastSpeech2 + HiFiGAN vocoder jointly. To run
# this config, you need to specify "--tts_task gan_tts"
# option for tts.sh at least and use 22050 hz audio as the
# training data (mainly tested on LJspeech).
# This configuration tested on 4 GPUs with 12GB GPU memory.
# It takes around 2 weeks to finish the training but 100k
# iters model should generate reasonable results.

##########################################################
#                  TTS MODEL SETTING                     #
##########################################################
tts: joint_text2wav
tts_conf:
    # copied from pretrained model's config.yaml
    text2mel_type: fastspeech2
    text2mel_params:
        adim: 384
        aheads: 2
        conformer_activation_type: swish
        conformer_dec_kernel_size: 31
        conformer_enc_kernel_size: 7
        conformer_pos_enc_layer_type: rel_pos
        conformer_self_attn_layer_type: rel_selfattn
        decoder_normalize_before: false
        decoder_type: conformer
        dlayers: 4
        dunits: 1536
        duration_predictor_chans: 256
        duration_predictor_kernel_size: 3
        duration_predictor_layers: 2
        elayers: 4
        encoder_normalize_before: false
        encoder_type: conformer
        energy_embed_dropout: 0.0
        energy_embed_kernel_size: 1
        energy_predictor_chans: 256
        energy_predictor_dropout: 0.5
        energy_predictor_kernel_size: 3
        energy_predictor_layers: 2
        eunits: 1536
        init_type: xavier_uniform
        pitch_embed_dropout: 0.0
        pitch_embed_kernel_size: 1
        pitch_predictor_chans: 256
        pitch_predictor_dropout: 0.5
        pitch_predictor_kernel_size: 5
        pitch_predictor_layers: 5
        positionwise_conv_kernel_size: 3
        positionwise_layer_type: conv1d
        postnet_chans: 256
        postnet_filts: 5
        postnet_layers: 5
        reduction_factor: 1
        stop_gradient_from_energy_predictor: false
        stop_gradient_from_pitch_predictor: true
        transformer_dec_attn_dropout_rate: 0.2
        transformer_dec_dropout_rate: 0.2
        transformer_dec_positional_dropout_rate: 0.2
        transformer_enc_attn_dropout_rate: 0.2
        transformer_enc_dropout_rate: 0.2
        transformer_enc_positional_dropout_rate: 0.2
        use_cnn_in_conformer: true
        use_macaron_style_in_conformer: true
        use_masking: true

    # copied from pretrained vocoder's config.yaml
    vocoder_type: hifigan_generator
    vocoder_params:
        bias: true
        channels: 512
        in_channels: 80
        kernel_size: 7
        nonlinear_activation: LeakyReLU
        nonlinear_activation_params:
            negative_slope: 0.1
        out_channels: 1
        resblock_dilations:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        resblock_kernel_sizes:
        - 3
        - 7
        - 11
        upsample_kernel_sizes:
        - 16
        - 16
        - 4
        - 4
        upsample_scales:
        - 8
        - 8
        - 2
        - 2
        use_additional_convs: true
        use_weight_norm: true

    # copied from pretrained vocoder's config.yaml
    discriminator_type: hifigan_multi_scale_multi_period_discriminator
    discriminator_params:
        follow_official_norm: true
        period_discriminator_params:
            bias: true
            channels: 32
            downsample_scales:
            - 3
            - 3
            - 3
            - 3
            - 1
            in_channels: 1
            kernel_sizes:
            - 5
            - 3
            max_downsample_channels: 1024
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
            use_spectral_norm: false
            use_weight_norm: true
        periods:
        - 2
        - 3
        - 5
        - 7
        - 11
        scale_discriminator_params:
            bias: true
            channels: 128
            downsample_scales:
            - 4
            - 4
            - 4
            - 4
            - 1
            in_channels: 1
            kernel_sizes:
            - 15
            - 41
            - 5
            - 3
            max_downsample_channels: 1024
            max_groups: 16
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
        scale_downsample_pooling: AvgPool1d
        scale_downsample_pooling_params:
            kernel_size: 4
            padding: 2
            stride: 2
        scales: 3

    # loss function related
    generator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    discriminator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    use_feat_match_loss: true            # whether to use feat match loss
    feat_match_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        average_by_layers: false         # whether to average loss value by #layers of each discriminator
        include_final_outputs: true      # whether to include final outputs for loss calculation
    use_mel_loss: true     # whether to use mel-spectrogram loss
    mel_loss_params:
        fs: 22050          # must be the same as the training data
        n_fft: 1024        # fft points
        hop_length: 256    # hop size
        win_length: null   # window length
        window: hann       # window type
        n_mels: 80         # number of Mel basis
        fmin: 0            # minimum frequency for Mel basis
        fmax: null         # maximum frequency for Mel basis
        log_base: null     # null represent natural log
    lambda_text2mel: 1.0   # loss scaling coefficient for text2mel loss
    lambda_adv: 1.0        # loss scaling coefficient for adversarial loss
    lambda_mel: 45.0       # loss scaling coefficient for Mel loss
    lambda_feat_match: 2.0 # loss scaling coefficient for feat match loss

    # others
    sampling_rate: 22050          # needed in the inference for saving wav
    segment_size: 32              # segment size for random windowed discriminator
    cache_generator_outputs: true # whether to cache generator outputs in the training

# extra module for additional inputs
pitch_extract: dio           # pitch extractor type
pitch_extract_conf:
    reduction_factor: 1
pitch_normalize: global_mvn  # normalizer for the pitch feature
energy_extract: energy       # energy extractor type
energy_extract_conf:
    reduction_factor: 1
energy_normalize: global_mvn # normalizer for the energy feature

# initialization
init_param:
- pretrain/59c43ac0d40b121060bd71dd418f5ece/exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth:tts:tts.generator.text2mel
- ljspeech.hifigan.v1/generator.pth::tts.generator.vocoder
- ljspeech.hifigan.v1/discriminator.pth::tts.discriminator

##########################################################
#            OPTIMIZER & SCHEDULER SETTING               #
##########################################################
# optimizer setting for generator
optim: adam
optim_conf:
    lr: 1.25e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
# optimizer setting for discriminator
optim2: adam
optim2_conf:
    lr: 1.25e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true # whether to start updating generator first

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 1000  # number of iterations per epoch
max_epoch: 2000            # number of epochs
accum_grad: 1             # gradient accumulation
batch_bins: 3000000       # batch bins (feats_type=raw)
batch_type: numel         # how to make batch
grad_clip: -1             # gradient clipping norm
grad_noise: false         # whether to use gradient noise injection
sort_in_batch: descending # how to sort data in making batch
sort_batch: descending    # how to sort created batches
num_workers: 0            # number of workers of data loader
use_amp: false            # whether to use pytorch amp
log_interval: 50          # log interval in iterations
keep_nbest_models: 5      # number of models to keep
num_att_plot: 3           # number of attention figures to be saved in every check
seed: 777                 # random seed number
patience: null            # patience for early stopping
#unused_parameters: true   # needed for multi gpu case
best_model_criterion:     # criterion to save the best models
-   - valid
    - text2mel_loss
    - min
-   - train
    - text2mel_loss
    - min
-   - train
    - total_count
    - max
```

**Comment by gafsd** [comment]
Yes the scheduler message appears during iterations but after it hangs it just prints 'pre_optim' and does not print 'pre_scheduler'
At the moment I suspect that it happened during other training but I can't confirm (no debug messages at those times and it took longer to hang so I am working on get debug output now)

**Comment by gafsd** [comment]
After 6 hours the other joint config now hang as well same section

```
2021-09-06 09:53:31,031 (gan_trainer:161) INFO: pre_model
2021-09-06 09:53:31,083 (gan_trainer:166) INFO: post_model
2021-09-06 09:53:31,085 (gan_trainer:219) INFO: pre_loss
2021-09-06 09:53:31,207 (gan_trainer:231) INFO: post_loss
2021-09-06 09:53:31,208 (gan_trainer:267) INFO: !!! pre_optim None <class 'torch.optim.adamw.AdamW'> 1/1
```

```
tts: joint_text2wav
tts_conf:
    # copied from pretrained model's config.yaml
    text2mel_type: fastspeech2
    text2mel_params:
        adim: 384
        aheads: 2
        conformer_activation_type: swish
        conformer_dec_kernel_size: 31
        conformer_enc_kernel_size: 7
        conformer_pos_enc_layer_type: rel_pos
        conformer_self_attn_layer_type: rel_selfattn
        decoder_normalize_before: false
        decoder_type: conformer
        dlayers: 4
        dunits: 1536
        duration_predictor_chans: 256
        duration_predictor_kernel_size: 3
        duration_predictor_layers: 2
        elayers: 4
        encoder_normalize_before: false
        encoder_type: conformer
        energy_embed_dropout: 0.0
        energy_embed_kernel_size: 1
        energy_predictor_chans: 256
        energy_predictor_dropout: 0.5
        energy_predictor_kernel_size: 3
        energy_predictor_layers: 2
        eunits: 1536
        init_type: xavier_uniform
        pitch_embed_dropout: 0.0
        pitch_embed_kernel_size: 1
        pitch_predictor_chans: 256
        pitch_predictor_dropout: 0.5
        pitch_predictor_kernel_size: 5
        pitch_predictor_layers: 5
        positionwise_conv_kernel_size: 3
        positionwise_layer_type: conv1d
        postnet_chans: 256
        postnet_filts: 5
        postnet_layers: 5
        reduction_factor: 1
        stop_gradient_from_energy_predictor: false
        stop_gradient_from_pitch_predictor: true
        transformer_dec_attn_dropout_rate: 0.2
        transformer_dec_dropout_rate: 0.2
        transformer_dec_positional_dropout_rate: 0.2
        transformer_enc_attn_dropout_rate: 0.2
        transformer_enc_dropout_rate: 0.2
        transformer_enc_positional_dropout_rate: 0.2
        use_cnn_in_conformer: true
        use_macaron_style_in_conformer: true
        use_masking: true

    # copied from pretrained vocoder's config.yaml
    vocoder_type: hifigan_generator
    vocoder_params:
        bias: true
        channels: 512
        in_channels: 80
        kernel_size: 7
        nonlinear_activation: LeakyReLU
        nonlinear_activation_params:
            negative_slope: 0.1
        out_channels: 1
        resblock_dilations:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        resblock_kernel_sizes:
        - 3
        - 7
        - 11
        upsample_kernel_sizes:
        - 16
        - 16
        - 4
        - 4
        upsample_scales:
        - 8
        - 8
        - 2
        - 2
        use_additional_convs: true
        use_weight_norm: true

    # discriminator related
    discriminator_type: hifigan_multi_scale_multi_period_discriminator
    discriminator_params:
        scales: 1
        scale_downsample_pooling: "AvgPool1d"
        scale_downsample_pooling_params:
            kernel_size: 4
            stride: 2
            padding: 2
        scale_discriminator_params:
            in_channels: 1
            out_channels: 1
            kernel_sizes: [15, 41, 5, 3]
            channels: 128
            max_downsample_channels: 1024
            max_groups: 16
            bias: True
            downsample_scales: [2, 2, 4, 4, 1]
            nonlinear_activation: "LeakyReLU"
            nonlinear_activation_params:
                negative_slope: 0.1
            use_weight_norm: True
            use_spectral_norm: False
        follow_official_norm: False
        periods: [2, 3, 5, 7, 11]
        period_discriminator_params:
            in_channels: 1
            out_channels: 1
            kernel_sizes: [5, 3]
            channels: 32
            downsample_scales: [3, 3, 3, 3, 1]
            max_downsample_channels: 1024
            bias: True
            nonlinear_activation: "LeakyReLU"
            nonlinear_activation_params:
                negative_slope: 0.1
            use_weight_norm: True
            use_spectral_norm: False

    # loss function related
    generator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    discriminator_adv_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        loss_type: mse                   # loss type, "mse" or "hinge"
    use_feat_match_loss: true            # whether to use feat match loss
    feat_match_loss_params:
        average_by_discriminators: false # whether to average loss value by #discriminators
        average_by_layers: false         # whether to average loss value by #layers of each discriminator
        include_final_outputs: true      # whether to include final outputs for loss calculation
    use_mel_loss: true     # whether to use mel-spectrogram loss
    mel_loss_params:
        fs: 22050          # must be the same as the training data
        n_fft: 1024        # fft points
        hop_length: 256    # hop size
        win_length: null   # window length
        window: hann       # window type
        n_mels: 80         # number of Mel basis
        fmin: 0            # minimum frequency for Mel basis
        fmax: null         # maximum frequency for Mel basis
        log_base: null     # null represent natural log
    lambda_text2mel: 1.0   # loss scaling coefficient for text2mel loss
    lambda_adv: 1.0        # loss scaling coefficient for adversarial loss
    lambda_mel: 45.0       # loss scaling coefficient for Mel loss
    lambda_feat_match: 2.0 # loss scaling coefficient for feat match loss

    # others
    sampling_rate: 22050          # needed in the inference for saving wav
    segment_size: 32              # segment size for random windowed discriminator
    cache_generator_outputs: true # whether to cache generator outputs in the training

# extra module for additional inputs
pitch_extract: dio           # pitch extractor type
pitch_extract_conf:
    reduction_factor: 1
pitch_normalize: global_mvn  # normalizer for the pitch feature
energy_extract: energy       # energy extractor type
energy_extract_conf:
    reduction_factor: 1
energy_normalize: global_mvn # normalizer for the energy feature

# initialization
init_param:
- pretrain/59c43ac0d40b121060bd71dd418f5ece/exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth:tts:tts.generator.text2mel
- ljspeech.hifigan.v1/generator.pth::tts.generator.vocoder

##########################################################
#            OPTIMIZER & SCHEDULER SETTING               #
##########################################################
# optimizer setting for generator
optim: adamw
optim_conf:
    lr: 2.0e-4
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
# optimizer setting for discriminator
optim2: adamw
optim2_conf:
    lr: 2.0e-4
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true # whether to start updating generator first

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 500  # number of iterations per epoch
max_epoch: 2000           # number of epochs
accum_grad: 1             # gradient accumulation
batch_bins: 3000000       # batch bins (feats_type=raw)
batch_type: numel         # how to make batch
grad_clip: -1             # gradient clipping norm
grad_noise: false         # whether to use gradient noise injection
sort_in_batch: descending # how to sort data in making batch
sort_batch: descending    # how to sort created batches
num_workers: 4            # number of workers of data loader
use_amp: false            # whether to use pytorch amp
log_interval: 10          # log interval in iterations
keep_nbest_models: 5      # number of models to keep
num_att_plot: 3           # number of attention figures to be saved in every check
seed: 777                 # random seed number
patience: null            # patience for early stopping
#unused_parameters: true   # needed for multi gpu case
best_model_criterion:     # criterion to save the best models
-   - train
    - total_count
    - max
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
```
