### ISSUE TITLE
How to make cross-lang transfer learning feasible? | Ampere RTX GPU support

### ISSUE THREAD

**Issue by cedilla1312** [espnet/espnet#3577]
1. Hey, I want to transfer learn (TL) selected English ASR model to Slovak ASR model.  
My 1st alternative is to use `Gigaspeech` (probably the one accessible at `Zenodo`)... or it could be `LibriSpeech` or `Voxforge` model, as well.
The 2nd alternative (depends on the obstacles/feasibility in ESPnet(v2) to transfer learn between languages) is to transfer learn some English ASR model (at `Zenodo` or` huggingfaceHub`) to Children's Speech EN ASR model - this shouldn't be a difficult challenge to start with.

After studying ESPnet docs, `TL` issues on Github, namely [#2667](https://github.com/espnet/espnet/issues/2667) [#2956](https://github.com/espnet/espnet/issues/2956), I have stumbled upon several possible obstacles. As my private Kaldi-formatted Slovak language dataset/s have different character lists in terms of size and chars (i.e. dictionaries - `data/lang_1char/train_nodev_units.txt`), computing power is limited (max. of 4x 1080Ti's) each with only 12GB of VRAM. 

BTW, I already have a pre-trained `RNNLM` + another type LM which I can't recall right now - LM should be incorporated, as well. I want to try TL instead from scratch as my prototype Slovak model on ESPnet1 was relatively promising (wo/ LM) on Transformer, however I've not been able to run Conformer on Slovak language (errors appeared).

1. Is it possible to successfully carry out TL with aforementioned conditions/setup?

2. Do you already support `Ampere` Nvidia Cards? I have seen [#3217](https://github.com/espnet/espnet/pull/3217) PR, so it looks like you do.

3. I could share precompiled `py wheels` for obsolete GPUs as it was quite difficult to make PyTorch, warp-rnnt, CUDA,... working /w e.g. K40 GPU (after PyTorch 1.4.0?). Anyway, I spotted some bugs (typos) or logical bugs during installation, but would have to again check on those, since I was hesitant to speak.

After I call to remembrance, the follow-up questions and information might be added.

**Comment by sw005320** [comment]
Thanks!
For cross-lang transfer learning of espent2, please check 
https://espnet.github.io/espnet/espnet2_training_option.html?highlight=fine%20tuning#transfer-learning-fine-tuning-using-pretrained-model

**Comment by cedilla1312** [comment]
After reading the whole docs and having practice with this SW, I seek answers
to these questions, while I can not find anybody to answer them - just devs, I'm rather desperate:

1. How do I increase GPU memory utilization (from `1G` to at least `10GB` for both 2x 1080 Ti) when running older [Shinji Watanabe/asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best](https://zenodo.org/record/4030511#.YhY5NZY1Wbg)
pretrained model with own Slovak `train`/`dev` data (using own Slovak `BPE model` taken from custom `egs2/` recipe)? 
Moreover, I have no idea when my retrain (fine-tune) task will finish - could be 1-2 weeks, or even a month... (50h of `TR`, 12h of `TEST` data).
After issuing `nvidia-smi`, only 1/10 of GPU is utilized, tried changing `accum_grad` (lowering it), `bins` (lowering), `batch_size ` (increasing) in `config.yaml`, according to [1167](https://github.com/espnet/espnet/issues/1167). To no avail. 
Despite that, GPU still leverages `1G/11GB` of VRAM. GPU `batching` algos worked flawlessly in `ESPnet1`, but it feels like pretrained model ignores `batch` params change.

2. Is it possible to define `token_type=char` while simultaneously defining `BPE model` path (in pretrained LibriSpeech by [sw005320](https://github.com/sw005320) in `config.yaml` file?
I was quite surprised that I can embed/define `BPE` model in `config.yaml` and concurrently set `token_type=character`. AFAIK `BPE` is a **sub-word** standalone compressing algorithm, however `python asr_train` outputs no error with different `token_types`. I feel like I miss theoretical grounds on this topic.

3. When I created my own recipe in `ESPnet2` [(EGS2 TEMPLATE)](https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE) the `conf/` `dir` is divided into `enc.` (`conf/tuning/transformer`...) and `decoder` part, whereas pretrained models have only one common `config.yaml` on Zenodo/HF.
How do I transfer base recipe configs (standard recipe in `egs2/`), consisting of encoder `conf/` and `dec` `conf/` `dir`s into single `config.yaml` to utilize in pretrained models?
Basically, I want to transfer own recipe training configs defined for e.g. `transformer` (in `egs2/config/`) into pretrained model's `config.yaml`.

4. After I created my own BPE `token_list` running custom Slovak recipe `--stage 10` (in standard `egs2` dir) to create BPE model usable in pretrained model by Shinji W. [(egs2/TEMPLATE/asr1/asr.sh#L634)](https://github.com/espnet/espnet/blob/cb8181a99bb59f8444b59a36c38878f95570faaf/egs2/TEMPLATE/asr1/asr.sh#L634), it was necessary to embed different Slovak `token_list` and replace original LibriSpeech `token_list` from `config.yaml` in `asr_train_asr_transformer_e18_raw_bpe_sp` pretrained model. Do you provide any `python_utils` to do that? I've checked all scripts, found none that could ease my job.

5. How do I print model layerwise structure (i.e. after running `python asr_train --...` in pretrained models) w/o **run**ning standard "egs2/" recipe from scratch? It starts with `ESPNet AbsModel(etc...)`.
It is useful when I want to document the model structure (let's say in paper) and I don't want to run given recipe myself. See appendix of this text. [Related #3948](https://github.com/espnet/espnet/issues/3948#issuecomment-1022040073).

6. One thing that bothers me is a lack of pretrained model fine-tuning progress. When I run `python asr_train --stage ...` script, there is no information on what is going on and when it's gonna finish its job. In `ESPnet1`, there used to be at least some info on pending process like gradients outputs...

7. When I want to fine-tune, transfer learn, e.g. Shinji's LibriSpeech model, to run model on different lang dataset firstly I need to facilitate 3 things for Shinji's pretrained `config.yaml` acquired from Zenodo:
**a)** different input speech **b)** corresponding output text and **c)** `shape_file`(.bpe/.scp). The former is easy, but for the latter (shape of `feats` file) I need to create run recipe from scratch in `ESPnet2` (run `stage 10`), then I acquire `shape_file` and finally I can reuse shape information in fine-tuning. Is there any straightforward way? I've found that shape file somehow relates to `common_write` func in ESPnet2 and it defines shape of feats so that batching algos: [](https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type) know how to handle & properly feed GPU with data.

8. I noticed that Shinji's pretrained model has `config.yaml` that does not define `test` data, only `dev` and `train`. How to explain this? How does ASR model then generalize on unknown data?

9. I'm currently retraining model [sw_e18](https://zenodo.org/record/4030511#.YhY5NZY1Wbg) on aforementioned custom Slovak dataset, but no data are saved, nor checkpoints in `data/` dir exist. `python asr_train` utilizes 100% of GPU, but no files are being created/modified. Please, see attached configs and setup below. I had to kill an `asr_train` script, no progress info and no files were created.

**Sorry for this long post and thanks for this exceptional SW, I buffer all these questions and then ask at once.**

git tag: **v.0.9.9**

**Pretrain model run cmd:**
```
python -m espnet2.bin.asr_train --init_param exp/asr_train_asr_transformer_e18_raw_bpe_sp/54epoch.pth 
--config exp/asr_train_asr_transformer_e18_raw_bpe_sp/kemt_svk1.yaml --token_list data/token_list/bpe_unigram5000/tokens.txt
```

- python version: `3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]`
- espnet version: `espnet 0.10.3a3`
- pytorch version: `pytorch 1.9.0`
- Git hash: `c6f8d6bd6e61c1fb945be3d8715f69dc7a7a17fb`
- Commit date: `Wed Sep 22 18:22:46 2021 +0900`

**Task:** [ASR]
**Recipe/Pretrained:** [librispeech_e18 pretrained + own Slovak dataset already in Kaldi format]
ESPnet2

```
python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.23

Python version: 3.9 (64-bit runtime)
Python platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.103.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89                       3    hcc
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.0            py39h42c9631_2
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] pytorch                   1.9.0           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
```

**config.yaml (edit on Shinji's public model e18 to use with Slovak data):
#batch options do nothing, still same VRAM utilization**
```
accum_grad: 1 #originally was 6
allow_variable_data_keys: false
batch_bins: 15000000 #from 15 mil /5
batch_size: 100 #changed from 20, is ignored for numel batch
batch_type: numel
best_model_criterion:
  - - valid
    - acc
    - max
bpemodel: data/token_list/bpe_unigram5000/bpe.model #token_list input through cmd pythom --asr_train...
chunk_length: 500
chunk_shift_ratio: 0.5
cleaner: null
collect_stats: true
config: conf/tuning/train_asr_transformer_e18.yaml
ctc_conf:
  ctc_type: builtin
  dropout_rate: 0
  reduce: true
cudnn_benchmark: false
cudnn_deterministic: true
cudnn_enabled: true
decoder: transformer
decoder_conf:
  attention_heads: 8
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 6
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
dry_run: false
early_stopping_criterion:
  - valid
  - loss
  - min
encoder: transformer
encoder_conf:
  attention_dropout_rate: 0.1
  attention_heads: 8
  dropout_rate: 0.1
  input_layer: conv2d6
  linear_units: 2048
  normalize_before: true
  num_blocks: 18
  output_size: 512
  positional_dropout_rate: 0.1
fold_length:
  - 80000
  - 150
frontend: default
frontend_conf:
  fs: 16k
g2p: null
grad_clip: 5
grad_noise: false
init: xavier_uniform
input_size: null
iterator_type: sequence
keep_nbest_models: 10
log_interval: null
log_level: INFO
max_cache_size: 0
max_epoch: 100
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
multiple_iterator: false
multiprocessing_distributed: false
ngpu: 2
no_forward_run: false
non_linguistic_symbols: null
normalize: global_mvn
normalize_conf: #npz file comes from egs2/ custom recipe
  stats_file: exp/asr_stats_raw_sp/train/feats_stats.npz
num_att_plot: 3
num_cache_chunks: 1024
num_iters_per_epoch: null
num_workers: 2 #num workers changed
optim: adam
optim_conf:
  lr: 0.002
output_dir: exp/BN_TUKE2_asr_train_asr_transf_e18_raw_bpe_sp
patience: null
print_config: false
resume: true
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
seed: 0
sort_batch: descending
sort_in_batch: descending
specaug: specaug
specaug_conf:
  apply_freq_mask: true
  apply_time_mask: true
  apply_time_warp: true
  freq_mask_width_range:
    - 0
    - 30
  num_freq_mask: 2
  num_time_mask: 2
  time_mask_width_range:
    - 0
    - 40
  time_warp_mode: bicubic
  time_warp_window: 5
token_type: char  # it's char, but I define BPE model thereinbefore
train_data_path_and_name_and_type:
  - - dump/raw/data_train_apvv17/wav.scp
    - speech
    - sound
  - - dump/raw/data_train_apvv17/text
    - text
    - text
train_dtype: float32
train_shape_file:
  - exp/asr_stats_raw_sp/train/speech_shape
  - exp/asr_stats_raw_sp/train/text_shape.bpe
use_preprocessor: true
val_scheduler_criterion:
  - valid
  - loss
valid_batch_bins: null
valid_batch_size: null
valid_batch_type: null
valid_data_path_and_name_and_type:
  - - dump/raw/data_dev_apvv17/wav.scp
    - speech
    - sound
  - - dump/raw/data_dev_apvv17/text
    - text
    - text
valid_max_cache_size: null
valid_shape_file:  #speech and text shape come from own base_recipe in egs2/
  - exp/asr_stats_raw_sp/valid/speech_shape  
  - exp/asr_stats_raw_sp/valid/text_shape.bpe
write_collected_feats: true
```

**Example for layerwise structure info (how do I print model struct w/o running `asr_train`?):**

```
        (feed_forward): PositionwiseFeedForward(
          (w_1): Linear(in_features=512, out_features=2048, bias=True)
          (w_2): Linear(in_features=2048, out_features=512, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (activation): ReLU()
        )
        (norm1): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
        (norm3): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (ctc): CTC(
    (ctc_lo): Linear(in_features=512, out_features=5000, bias=True)
    (ctc_loss): CTCLoss()
  )
  (criterion_att): LabelSmoothingLoss(
    (criterion): KLDivLoss()
  )
)

Model summary:
    Class Name: ESPnetASRModel
    Total Number of model parameters: 99.36 M
    Number of trainable parameters: 99.36 M (100.0%)
    Size: 397.46 MB
    Type: torch.float32
[quadro] 2022-02-15 02:27:11,990 (abs_task:1136) INFO: Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
```
