### ISSUE TITLE
Recipe for training Conformer with LibriSpeech train-100h using ESPnet2

### ISSUE THREAD

**Issue by asadolahzade** [espnet/espnet#3889]
Hi,
I'd like to train a conformer model with train-100 hours of LibriSpeech corpus using ESPnet2. 
Please if someone has any experience share with me what changes of parameters or hyperparameters (e.g. lr, ...) I should make to the current recipe of LS-960 to train this model? Let me know for any point I should consider for training conformer with this amount of data?
Thanks a lot for any help.

**Comment by sw005320** [comment]
@YosukeHiguchi has a very good configuration but it is based on espnet1 (in my understanding. Correct me if I'm wrong), but he will make a recipe for train-100 hours of LibriSpeech in the near future based on espnet2.
@YosukeHiguchi, can you let me know your plan?
Would it happen in the next year?

**Comment by YosukeHiguchi** [comment]
Hi @asadolahzade, I can share my conformer configuration on LS-100 (train-clean-100):
```yaml
elayers: 12
eunits: 2048
adim: 256
aheads: 4

mtlalpha: 1.0

lsm-weight: 0.1

batch-size: 64
maxlen-in: 512
maxlen-out: 150

sortagrad: 0
opt: noam
accum-grad: 4
grad-clip: 5
patience: 0
epochs: 150
dropout-rate: 0.1

backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_conformer:E2E"
transformer-input-layer: conv2d     # encoder architecture type
transformer-lr: 5.0
transformer-warmup-steps: 25000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: false
transformer-init: pytorch

transformer-encoder-activation-type: swish
transformer-encoder-pos-enc-layer-type: rel_pos
transformer-encoder-selfattn-layer-type: rel_selfattn
macaron-style: true
use-cnn-module: true
cnn-module-kernel: 31
rel-pos-type: latest
```
Please note that the above configuration is for espnet1 and assumes a single GPU training. I hope this helps you to tune a model on espnet2.

@sw005320, I'm planning to prepare the LS-100 recipe on espnet1 (and espnet2). Sorry for being late but I will do it by the end of this year.

**Comment by sw005320** [comment]
Thanks, @YosukeHiguchi!
I'm looking forward to your PR!

**Comment by asadolahzade** [comment]
Hi @YosukeHiguchi , 
Thanks a lot for your recipe.
I'm looking forward to your recipe in ESPnet2 too. Meanwhile, I try to tune your ESPnet1 recipe.
Thanks a lot.

**Comment by asadolahzade** [comment]
Hi @YosukeHiguchi , 

I changed the recipe of training LS-960 (https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_n_fft512_hop_length256.yaml) based on your recipe of LS-100 as follows:
```
batch_type: numel
batch_bins: 140000000
accum_grad: 1
max_epoch: 150
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
     ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0025
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 40000

frontend_conf:
  n_fft: 512
  hop_length: 256

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
```
But I'm not sure about some hyper-parameters. I keep the list following the same as the recipe of the above link.
Are they suitable in your opinion? If not, could you help me with how to set them?

1) ```batch_bins: 140000000``` and ```accum_grad: 1```. 

2) ```lr: 0.0025``` and ```warmup_steps: 40000```

3) ```dropout_rate``` related parameters like ```attention_dropout_rate``` and so on.

4) The value of ```--nbpe``` for LS-960 is 5000. Should I change it for LS-100?


5) I have another question regarding the number of layers for encoder and decoder. 
I wonder why you use the same number of layers for both 960h and 100h?
Don't we need to reduce them for smaller data like 100hr? 


Thank you so much for your help.
