### ISSUE TITLE
how to use s3prl frontend with local model file

### ISSUE THREAD

**Issue by pkyoung** [espnet/espnet#3961]
how to set configuraiton file to use local pretrained model with s3prl frontend.
In example config,  wav2vec2 model automatically downloaded as specified in upstream.
What if I have my own wav2vec2 model, and want to use it, then how can I set the config?

```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_large_ll60k  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: true
```

**Comment by simpleoier** [comment]
@pkyoung It's a good question. We actually mainly considered the  pretrained models from s3prl. You definitely can use the local pretrained models. But it may require more complicated configurations. I  don't have an exact solution right now. 
I suggest you to try  the following config:
```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_local  # Note: If the upstream is changed, please change the input_size in the preencoder.
        upstream_ckpt: "path/to/your/ckpt"
        pstream_model_config: "config/of/your/model"
    download_dir: ./hub
    multilayer_feature: true
```
I don't have a specific ckpt and corresponding config right now. It  may require more arguments in the `frontend_conf.frontend_conf`. The basic information can be found [here](https://github.com/simpleoier/espnet/blob/b4cd04ce012292725ebbe363449cf5decd497be3/espnet2/asr/frontend/s3prl.py#L19). Please let me know if it does not work.

**Comment by pkyoung** [comment]
I am not working on this stuff right at the moment.
Sooner or later, I will give it a shot and let you know how it works.
Thanks.

**Comment by pkyoung** [comment]
@simpleoier  The conf as following did the job. Thanks.
```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_local  
        upstream_ckpt: "path/to/my/ckpt"
    multilayer_feature: true
```
