### ISSUE TITLE
Is it possible to get the erased noise wav file?

### ISSUE THREAD

**Issue by Taruguchi** [espnet/espnet#4473]
I am trying speech enhancement using `vctk_noisy` recipe.
I use transformer, and the noises are disappeared and clear voices are inferenced.

I want to get not only clear voices but also the disappeared noises as wav files.
Is it possible?

**Comment by Emrys365** [comment]
By default, the current SE training process will only use the speech signal as the target, so you cannot obtain the noise signal from the noisy input directly.
However, if you retrain the model by including another noise estimation loss, i.e., predicting both speech and noise signals at the same time, you can then easily extract the noise signal from the noisy input.

> We used to support using noise as another training target, but after some refactoring, we temporarily disabled this function in `espnet2/enh/espnet_model.py`. We will restore rhis function later but it may take some time. To make it work again by yourself, you will need to add some code manually in that script to calculate loss on the estimated noise signal. Then, you could pass `--use_noise_ref true` to `run.sh` to load the noise signals for training.

**Comment by Taruguchi** [comment]
Thank you for your answer.
I dont know what script to add to `espnet_model.py`, so please tell me the script I need to add.
Or, should I wait for the restoring function?

I understood that after Adding the script, each of the signal and noise will be learned.
And the time of inference, I can get two sounds, signal and noise. 
Thats right?

**Comment by Emrys365** [comment]
> I understood that after Adding the script, each of the signal and noise will be learned.
> And the time of inference, I can get two sounds, signal and noise.
> Thats right?

Yes, the output during training and inference should be consistent in general SE models, so you can obtain both speech and noise signals as long as the model is configured to do so.

**Comment by Emrys365** [comment]
@Taruguchi You also need to modify the model configuration file to set `predict_noise` to True and add a loss for the noise signal. For example:

```yaml
separator: tcn
separator_conf:
    num_spk: 1
    ...
    predict_noise: true

...
criterions: 
  # The first criterion
  - name: si_snr
    conf:
      clamp_db: 70
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
  # The second criterion (for noise estimation)
  - name: si_snr_noise
    conf:
      clamp_db: 70
      is_noise_loss: true
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
```
