### ISSUE TITLE
decode speed is very slow on gpu

### ISSUE THREAD

**Issue by v-yunbin** [espnet/espnet#4485]
i use asr_inference.py and pretrained aishell model to decode on gpu，a 9.3s audio cost 6minutes to decode on gpu.

**Comment by v-yunbin** [comment]
> i use asr_inference.py and pretrained aishell model to decode on gpu，a 9.3s audio cost 6minutes to decode on gpu.

update，last time， when I test the speed，other training is going, the real speed is a 9.3s audio cost 16.9s to decode on gpu.

**Comment by sw005320** [comment]
Can you report the cpu speed?
Also, can you show us the inference config file?

**Comment by v-yunbin** [comment]
@sw005320 
1. teset script
```
import soundfile
import sys
from espnet2.bin.asr_inference import Speech2Text
speech2text = Speech2Text(asr_train_config="espnet_model/wenet/config.yaml", asr_model_file="espnet_model/wenet/valid.acc.ave_10best.pth", device="cpu")
# Confirm the sampling rate is equal to that of the training corpus.
# If not, you need to resample the audio data before inputting to speech2text
speech, rate = soundfile.read(sys.argv[1])
nbests = speech2text(speech)

text, *_ = nbests[0]
print(text)
```
2. config file（from wenet pretrained model）：
```
config: conf/train_asr_conformer.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/asr_train_asr_conformer_raw_zh_char
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 8
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 44205
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 30
patience: null
val_scheduler_criterion:
- valid
- acc
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
grad_clip: 5
grad_clip_type: 2.0
grad_noise: false
accum_grad: 4
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_tensorboard: true
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 30000000
valid_batch_bins: null
train_shape_file:
- exp/asr_stats_raw_zh_char/train/speech_shape
- exp/asr_stats_raw_zh_char/train/text_shape.char
valid_shape_file:
- exp/asr_stats_raw_zh_char/valid/speech_shape
- exp/asr_stats_raw_zh_char/valid/text_shape.char
batch_type: numel
valid_batch_type: null
fold_length:
- 51200
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train_l/wav.scp
    - speech
    - sound
-   - dump/raw/train_l/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/raw/dev/wav.scp
    - speech
    - sound
-   - dump/raw/dev/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000
token_list:
```
4. test the speed cpu vs gpu on  a 9.3s audio:
```
cpu: 0m17.365s( include time of loading model)
gpu: 1m0.642s include time of loading model)
```
