### ISSUE TITLE
RNN-T Decoding - Large Number of Deletions Compared to Transformer/Conformer

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#4540]
I am getting a lot of deletions in my RNN-T training/decoding setup relative to Transformer/Conformer. The data is the "Malach" corpus; about 200 hours of English but accented speech from Holocaust survivors.  Appreciate any insights/suggestions anyone may have!

This is the sclite outputs from all three systems:

|  Condition  |  # Snt  | # Wrd  |  Corr | Sub | Del | Ins | Err | S.Err |
| - | - | - | - | - | - | - | - | - |
|  Transformer  |  1155 | 12256 | 82.0 | 13.6 | 4.3 | 4.8 | 22.8 | 68.1 |
|  RNN-T  | 1155  | 12256 | 70.4 | 13.5 | 16.1 | 2.7 | 32.3 | 73.9 |
|  Conformer  |  1155 | 12256 | 81.8 | 12.9 | 5.3 | 4.1 | 22.3 | 68.4 |

I also attached training and decoding configs for the RNN-T. 

This is the training config for the RNNT:

```
# The conformer transducer training configuration from @jeon30c
# WERs for test-clean/test-other are 2.9 and 7.2, respectively.
# Trained with Tesla V100-SXM2(32GB) x 8 GPUs. It takes about 1.5 days.
batch_type: numel
batch_bins: 20000000
accum_grad: 2
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

model_conf:
    ctc_weight: 0.0
    report_cer: False
    report_wer: False

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 512
    dropout: 0.1
    dropout_embed: 0.1

joint_net_conf:
    joint_space_size: 640

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 160 

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
```

This is the decoding config:

```
# The conformer transducer decoding configuration from @jeon30c
beam_size: 10
transducer_conf:
    search_type: default
    score_norm: True
```
