### ISSUE TITLE
Get errors when trying to train multi-speaker tacotron 2

### ISSUE THREAD

**Issue by blackmamba1122** [espnet/espnet#4730]
**Describe the bug**

**Basic environments:**
 - OS information: [Linux 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64]
 - python version: [3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]]
 - espnet version: [espnet 202207]
 - Git hash [14fcb2d42b2609f766ffaa7a79e9c921cd8398d]
   - Commit date [Tue Sep 27 20:02:22 2022 +0000]
 - pytorch version [pytorch 1.12.1+cu102]
 

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.12.1
[pip3] torch-complex==0.4.3
[conda] Could not collect

```

**Task information:**
 - Task: [TTS]
 - Recipe: [espnet/egs2/vctk/tts1]
 - ESPnet1 or ESPnet2

**To Reproduce**
1. move to a recipe directory `cd tacotron2/tts1`
2. execute `run.sh` with specific arguments ```./tts.sh --stage 6 --stop_stage 6 --train_args '--batch_size 4 --batch_type folded --max_epoch 3000' --ngpu 1 --skip_eval true --nj 6 --inference_nj 6 --audio_format wav --use_sid true --train_set train --valid_set val --test_sets test --srctexts data/train/text --train_config /media/DATA-2/TTS/Espnet/espnet/egs2/vctk/tts1/conf/tuning/multi_tacotron.yaml --stage 6 "$@"; exit $?```
3. specify the error log, e.g., `/media/DATA-2/TTS/Espnet/espnet/egs2/Tacotron2/tts1/exp/tts_multi_tacotron_raw_phn_tacotron_g2p_en_batch_size4_batch_typefolded_max_epoch3000/train.log`

**Error logs**
```
# python3 -m espnet2.bin.tts_train --use_preprocessor true --token_type phn --token_list dump/token_list/phn_tacotron_g2p_en/tokens.txt --non_linguistic_symbols none --cleaner tacotron --g2p g2p_en --normalize global_mvn --resume true --fold_length 150 --fold_length 204800 --output_dir exp/tts_multi_tacotron_raw_phn_tacotron_g2p_en_batch_size4_batch_typefolded_max_epoch3000 --config /media/DATA-2/TTS/Espnet/espnet/egs2/vctk/tts1/conf/tuning/multi_tacotron.yaml --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=16000 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --train_data_path_and_name_and_type dump/raw/train/text,text,text --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/train/text_shape.phn --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/train/speech_shape --valid_data_path_and_name_and_type dump/raw/val/text,text,text --valid_data_path_and_name_and_type dump/raw/val/wav.scp,speech,sound --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/valid/text_shape.phn --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/valid/speech_shape --train_data_path_and_name_and_type dump/raw/train/utt2sid,sids,text_int --valid_data_path_and_name_and_type dump/raw/val/utt2sid,sids,text_int --normalize_conf stats_file=exp/tts_stats_raw_phn_tacotron_g2p_en/train/feats_stats.npz --batch_size 4 --batch_type folded --max_epoch 3000 --ngpu 1 --multiprocessing_distributed True 
# Started at Mon Oct 24 09:47:07 WIB 2022
#
/media/DATA-2/TTS/Espnet/espnet_env/bin/python3 /media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/bin/tts_train.py --use_preprocessor true --token_type phn --token_list dump/token_list/phn_tacotron_g2p_en/tokens.txt --non_linguistic_symbols none --cleaner tacotron --g2p g2p_en --normalize global_mvn --resume true --fold_length 150 --fold_length 204800 --output_dir exp/tts_multi_tacotron_raw_phn_tacotron_g2p_en_batch_size4_batch_typefolded_max_epoch3000 --config /media/DATA-2/TTS/Espnet/espnet/egs2/vctk/tts1/conf/tuning/multi_tacotron.yaml --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=16000 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --train_data_path_and_name_and_type dump/raw/train/text,text,text --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/train/text_shape.phn --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/train/speech_shape --valid_data_path_and_name_and_type dump/raw/val/text,text,text --valid_data_path_and_name_and_type dump/raw/val/wav.scp,speech,sound --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/valid/text_shape.phn --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en/valid/speech_shape --train_data_path_and_name_and_type dump/raw/train/utt2sid,sids,text_int --valid_data_path_and_name_and_type dump/raw/val/utt2sid,sids,text_int --normalize_conf stats_file=exp/tts_stats_raw_phn_tacotron_g2p_en/train/feats_stats.npz --batch_size 4 --batch_type folded --max_epoch 3000 --ngpu 1 --multiprocessing_distributed True
[H310M-H-2-0] 2022-10-24 09:47:10,229 (tts:291) INFO: Vocabulary size: 78
[H310M-H-2-0] 2022-10-24 09:47:12,629 (abs_task:1157) INFO: pytorch.version=1.12.1+cu102, cuda.available=True, cudnn.version=7605, cudnn.benchmark=False, cudnn.deterministic=True
[H310M-H-2-0] 2022-10-24 09:47:12,630 (abs_task:1158) INFO: Model structure:
ESPnetTTSModel(
  (feats_extract): LogMelFbank(
    (stft): Stft(n_fft=1024, win_length=1024, hop_length=256, center=True, normalized=False, onesided=True)
    (logmel): LogMel(sr=16000, n_fft=1024, n_mels=80, fmin=80, fmax=7600, htk=False)
  )
  (normalize): GlobalMVN(stats_file=exp/tts_stats_raw_phn_tacotron_g2p_en/train/feats_stats.npz, norm_means=True, norm_vars=True)
  (tts): Tacotron2(
    (enc): Encoder(
      (embed): Embedding(78, 512, padding_idx=0)
      (convs): ModuleList(
        (0): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
        (1): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
        (2): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
      )
      (blstm): LSTM(512, 256, batch_first=True, bidirectional=True)
    )
    (sid_emb): Embedding(4, 512)
    (dec): Decoder(
      (att): AttLoc(
        (mlp_enc): Linear(in_features=512, out_features=512, bias=True)
        (mlp_dec): Linear(in_features=1024, out_features=512, bias=False)
        (mlp_att): Linear(in_features=32, out_features=512, bias=False)
        (loc_conv): Conv2d(1, 32, kernel_size=(1, 31), stride=(1, 1), padding=(0, 15), bias=False)
        (gvec): Linear(in_features=512, out_features=1, bias=True)
      )
      (lstm): ModuleList(
        (0): ZoneOutCell(
          (cell): LSTMCell(768, 1024)
        )
        (1): ZoneOutCell(
          (cell): LSTMCell(1024, 1024)
        )
      )
      (prenet): Prenet(
        (prenet): ModuleList(
          (0): Sequential(
            (0): Linear(in_features=80, out_features=256, bias=True)
            (1): ReLU()
          )
          (1): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): ReLU()
          )
        )
      )
      (postnet): Postnet(
        (postnet): ModuleList(
          (0): Sequential(
            (0): Conv1d(80, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (1): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (2): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (3): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (4): Sequential(
            (0): Conv1d(512, 80, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Dropout(p=0.5, inplace=False)
          )
        )
      )
      (feat_out): Linear(in_features=1536, out_features=80, bias=False)
      (prob_out): Linear(in_features=1536, out_features=1, bias=True)
    )
    (taco2_loss): Tacotron2Loss(
      (l1_criterion): L1Loss()
      (mse_criterion): MSELoss()
      (bce_criterion): BCEWithLogitsLoss()
    )
    (attn_loss): GuidedAttentionLoss()
  )
)

Model summary:
    Class Name: ESPnetTTSModel
    Total Number of model parameters: 26.66 M
    Number of trainable parameters: 26.66 M (100.0%)
    Size: 106.64 MB
    Type: torch.float32
[H310M-H-2-0] 2022-10-24 09:47:12,630 (abs_task:1161) INFO: Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-06
    foreach: None
    lr: 0.001
    maximize: False
    weight_decay: 0.0
)
[H310M-H-2-0] 2022-10-24 09:47:12,630 (abs_task:1162) INFO: Scheduler: None
[H310M-H-2-0] 2022-10-24 09:47:12,631 (abs_task:1171) INFO: Saving the configuration in exp/tts_multi_tacotron_raw_phn_tacotron_g2p_en_batch_size4_batch_typefolded_max_epoch3000/config.yaml
[H310M-H-2-0] 2022-10-24 09:47:12,784 (abs_task:1525) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/train/text", "type": "text"}
  speech: {"path": "dump/raw/train/wav.scp", "type": "sound"}
  sids: {"path": "dump/raw/train/utt2sid", "type": "text_int"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f602cc13940>)
[H310M-H-2-0] 2022-10-24 09:47:12,784 (abs_task:1526) INFO: [train] Batch sampler: FoldedBatchSampler(N-batch=845, batch_size=4, shape_files=['exp/tts_stats_raw_phn_tacotron_g2p_en/train/text_shape.phn', 'exp/tts_stats_raw_phn_tacotron_g2p_en/train/speech_shape'], sort_in_batch=descending, sort_batch=descending)
[H310M-H-2-0] 2022-10-24 09:47:12,784 (abs_task:1527) INFO: [train] mini-batch sizes summary: N-batch=845, mean=3.8, min=2, max=4
[H310M-H-2-0] 2022-10-24 09:47:12,797 (abs_task:1525) INFO: [valid] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/val/text", "type": "text"}
  speech: {"path": "dump/raw/val/wav.scp", "type": "sound"}
  sids: {"path": "dump/raw/val/utt2sid", "type": "text_int"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f602cc13d60>)
[H310M-H-2-0] 2022-10-24 09:47:12,798 (abs_task:1526) INFO: [valid] Batch sampler: FoldedBatchSampler(N-batch=104, batch_size=4, shape_files=['exp/tts_stats_raw_phn_tacotron_g2p_en/valid/text_shape.phn', 'exp/tts_stats_raw_phn_tacotron_g2p_en/valid/speech_shape'], sort_in_batch=descending, sort_batch=descending)
[H310M-H-2-0] 2022-10-24 09:47:12,798 (abs_task:1527) INFO: [valid] mini-batch sizes summary: N-batch=104, mean=3.8, min=2, max=4
[H310M-H-2-0] 2022-10-24 09:47:12,808 (abs_task:1525) INFO: [plot_att] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/val/text", "type": "text"}
  speech: {"path": "dump/raw/val/wav.scp", "type": "sound"}
  sids: {"path": "dump/raw/val/utt2sid", "type": "text_int"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f602c9d32b0>)
[H310M-H-2-0] 2022-10-24 09:47:12,809 (abs_task:1526) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=396, batch_size=1, key_file=exp/tts_stats_raw_phn_tacotron_g2p_en/valid/text_shape.phn, 
[H310M-H-2-0] 2022-10-24 09:47:12,809 (abs_task:1527) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[H310M-H-2-0] 2022-10-24 09:47:12,931 (trainer:276) INFO: 1/3000epoch started
../aten/src/ATen/native/cuda/Indexing.cu:922: indexSelectSmallIndex: block: [2,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
.
.
.
../aten/src/ATen/native/cuda/Indexing.cu:922: indexSelectSmallIndex: block: [1,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/layers/stft.py:164: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.n_fft) // self.hop_length + 1
/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/train/trainer.py", line 282, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/train/trainer.py", line 556, in train_one_epoch
    retval = model(**batch)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/tts/espnet_model.py", line 151, in forward
    return self.tts(**batch)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/tts/tacotron2/tacotron2.py", line 324, in forward
    after_outs, before_outs, logits, att_ws = self._forward(
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet2/tts/tacotron2/tacotron2.py", line 409, in _forward
    return self.dec(hs, hlens, ys)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet/nets/pytorch_backend/tacotron2/decoder.py", line 436, in forward
    att_c, att_w = self.att(hs, hlens, z_list[0], prev_att_w)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/DATA-2/TTS/Espnet/espnet_env/lib/python3.8/site-packages/espnet/nets/pytorch_backend/rnn/attentions.py", line 340, in forward
    att_prev = 1.0 - make_pad_mask(enc_hs_len).to(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
# Accounting: time=8 threads=1
# Ended (code 1) at Mon Oct 24 09:47:15 WIB 2022, elapsed time 8 seconds

```

**Comment by kan-bayashi** [comment]
Maybe the same as https://github.com/espnet/espnet/issues/4301
You need to spks=4 -> spks=5 since 0 is reserved for unknown spk.

**Comment by blackmamba1122** [comment]
> Maybe the same as #4301 You need to spks=4 -> spks=5 since 0 is reserved for unknown spk.

Yup, I know. But I got this error when I adding spks: 4 in config.yaml

```
# This configuration is for ESPnet2 to train GST-Tacotron 2. Compared to the
# original paper, this configuration additionally use the guided attention
# loss to accelerate the learning of the diagonal attention. It takes around
# 4 days to finish the training on RTX Titan.

##########################################################
#                  TTS MODEL SETTING                     #
##########################################################
tts: tacotron2                   # model architecture
tts_conf:                        # keyword arguments for the selected model
    **spks: 4**
    embed_dim: 512               # char or phn embedding dimension
    elayers: 1                   # number of blstm layers in encoder
    eunits: 512                  # number of blstm units
    econv_layers: 3              # number of convolutional layers in encoder
    econv_chans: 512             # number of channels in convolutional layer
    econv_filts: 5               # filter size of convolutional layer
    atype: location              # attention function type
    adim: 512                    # attention dimension
    aconv_chans: 32              # number of channels in convolutional layer of attention
    aconv_filts: 15              # filter size of convolutional layer of attention
    cumulate_att_w: true         # whether to cumulate attention weight
    dlayers: 2                   # number of lstm layers in decoder
    dunits: 1024                 # number of lstm units in decoder
    prenet_layers: 2             # number of layers in prenet
    prenet_units: 256            # number of units in prenet
    postnet_layers: 5            # number of layers in postnet
    postnet_chans: 512           # number of channels in postnet
    postnet_filts: 5             # filter size of postnet layer
    output_activation: null      # activation function for the final output
    use_batch_norm: true         # whether to use batch normalization in encoder
    use_concate: true            # whether to concatenate encoder embedding with decoder outputs
    use_residual: false          # whether to use residual connection in encoder
    use_gst: true                # whether to use GST embedding
    gst_heads: 8                 # number of heads in GST multi-head attention
    gst_tokens: 128              # number of global style tokens
    dropout_rate: 0.5            # dropout rate
    zoneout_rate: 0.1            # zoneout rate
    reduction_factor: 1          # reduction factor
    spk_embed_dim: null          # speaker embedding dimension
    use_masking: true            # whether to apply masking for padded part in loss calculation
    bce_pos_weight: 10.0         # weight of positive sample in binary cross entropy calculation
    use_guided_attn_loss: true   # whether to use guided attention loss
    guided_attn_loss_sigma: 0.4  # sigma of guided attention loss
    guided_attn_loss_lambda: 1.0 # strength of guided attention loss

##########################################################
#                  OPTIMIZER SETTING                     #
##########################################################
optim: adam           # optimizer type
optim_conf:           # keyword arguments for selected optimizer
    lr: 1.0e-03       # learning rate
    eps: 1.0e-06      # epsilon
    weight_decay: 0.0 # weight decay coefficient

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 500    # number of iterations per epoch
max_epoch: 300              # number of epochs
grad_clip: 1.0              # gradient clipping norm
grad_noise: false           # whether to use gradient noise injection
accum_grad: 1               # gradient accumulation
# batch_bins: 1000000       # batch bins (for feats_type=fbank)
batch_bins: 3750000         # batch bins (for feats_type=raw, *= n_shift / n_mels)
batch_type: numel           # how to make batch
sort_in_batch: descending   # how to sort data in making batch
sort_batch: descending      # how to sort created batches
num_workers: 1              # number of workers of data loader
train_dtype: float32        # dtype in training
log_interval: null          # log interval in iterations
keep_nbest_models: 5        # number of models to keep
num_att_plot: 3             # number of attention figures to be saved in every check
seed: 0                     # random seed number
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min

```
