### ISSUE TITLE
How to stream speech enhancement?

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [espnet/espnet#4760]
Hello.

I want to process the microphone input signal with the speech enhancement.
For testing, I split the file and processed it as shown in the code below.

```Python
from espnet2.bin.enh_inference import *
import soundfile
import time

pth_yaml_dir = "./pth_yaml_origin/"

def main():
    separate_speech_frm = SeparateSpeech(pth_yaml_dir + "/sep_trans.yaml", pth_yaml_dir + "coef.pth", normalize_output_wav=False)
    audio, rate = soundfile.read("mic.wav")

    #frame processing
    start_time = time.perf_counter()
    frame_size = 3072
    frame_num = int(len(audio) / frame_size)
    out_data = np.zeros(0)

    for i in range(frame_num):
        data = audio[i*frame_size:(i+1)*frame_size]
        input = data[np.newaxis, :]
        separated_audio = separate_speech_frm(input)
        out_data = np.append(out_data, separated_audio[0].reshape(-1) * 0.5)

    execution_time = time.perf_counter() - start_time
    
    soundfile.write("separated_frm.wav", out_data, rate, format="WAV", subtype="PCM_16")
    print(f'execution_time:{execution_time:.5f}[sec]')

if __name__ == "__main__":
    main()
```

However, every frame, an odd noise occurred. (see waveform and spectrogram below)

![1](https://user-images.githubusercontent.com/104180422/200788516-d9098df4-c97d-4490-b22c-d91e539158c7.PNG)

Is there any way to make the speech enhance task work with streaming?

Best regards.

**Comment by Emrys365** [comment]
It seems you manually divided the input audio into frames, and fed the model one frame at a time. This is very different from how the model was trained, and thus can introduce some unexpected artifacts in the output.

Actually, we provided the block-online style processing functionality. You could try the following code:
```python
separate_speech_frm = SeparateSpeech(
    pth_yaml_dir + "/sep_trans.yaml",
    pth_yaml_dir + "coef.pth",
    segment_size=0.5,  # process 0.5-sec audio at a time
    hop_size=0.25,     # the sliding window moves forward 0.25 sec for each block
    normalize_segment_scale=True,
    normalize_output_wav=False,
)
out_data  = separate_speech_frm(audio)
```

**Comment by Shin-ichi-Takayama** [comment]
@Emrys365 
Thank you for your response.

I have tried the method you suggested.
However, the frame-by-frame noise remains.
Are segment_size and hop_size not appropriate?
The method you suggested is processing the signals in batches, but how can I process the microphone signals in streaming?

![2](https://user-images.githubusercontent.com/104180422/200981243-5502bb6b-d14c-4f3e-b7b3-ceeb8f485feb.PNG)

The code is as follows

```Python
from espnet2.bin.enh_inference import *
import soundfile
import time

pth_yaml_dir = "./pth_yaml_origin/"

def main():
    separate_speech_frm = SeparateSpeech(
        pth_yaml_dir + "/sep_trans.yaml",
        pth_yaml_dir + "coef.pth",
        segment_size=0.5,  # process 0.5-sec audio at a time
        hop_size=0.25,     # the sliding window moves forward 0.25 sec for each block
        normalize_segment_scale=True,
        normalize_output_wav=False,
    )
    audio, rate = soundfile.read("mic.wav")

    start_time = time.perf_counter()
    input = audio[np.newaxis, :]
    separated_audio = separate_speech_frm(input)
    separated_audio = separated_audio[0].reshape(-1) * 0.5
    execution_time = time.perf_counter() - start_time
    soundfile.write("separated_hop.wav", separated_audio, rate, format="WAV", subtype="PCM_16")

    execution_time = time.perf_counter() - start_time

    print(f'execution_time:{execution_time:.5f}[sec]')
    

if __name__ == "__main__":
    main()

```

The settings during learning are as follows
```yaml
optim: adam
init: xavier_uniform
max_epoch: 300
batch_type: folded
batch_size:  8
num_workers: 4
optim_conf:
    lr: 1.0e-04
    eps: 1.0e-08
    weight_decay: 1.0e-7
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.7
    patience: 1

encoder: stft
encoder_conf:
    n_fft: 512
    hop_length: 128
decoder: stft
decoder_conf:
    n_fft: 512
    hop_length: 128
separator: transformer
separator_conf:
    num_spk: 1
    adim: 384
    aheads: 4
    layers: 6
    linear_units: 1536
    nonlinear: relu
    positionwise_layer_type: linear
    positionwise_conv_kernel_size: 1
    normalize_before: False
    concat_after: False
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    predict_noise: true


# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions: 
  # The first criterion
  - name: si_snr
    conf:
      clamp_db: 70
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
  # The second criterion (for noise estimation)
  - name: si_snr
    conf:
      clamp_db: 70
      is_noise_loss: true
      name: si_snr_noise
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
      
model_conf:
    stft_consistency: false
    loss_type: mask_mse
    mask_type: null
```
