### ISSUE TITLE
espnet2 EEND callhome recipe

### ISSUE THREAD

**Issue by msh9184** [espnet/espnet#5295]
Hi, thank you for the great work.
I'm trying to run the end-to-end neural speaker diarization recipe using CALLHOME benchmark (simulated mixtures and CALLHOME in-domain adaptation sets).
However, when I ran the SA-EEND (or EEND-EDA) models after preparing the simulated mixtures and CALLHOME datasets and format of kaldi-style, I get an out-of-memory error no matter how small the batch size is.

Is there any recipe or guideline for EEND training of the CALLHOME benchmark?

**Comment by sw005320** [comment]
Thanks for the report.
Actually, making a CALLHOME benchmark with EEND is one of our action items.
Thanks for triggering it.

Could you tell me how to run it?
Can you share your config, recipe scripts, etc so that we can help figure out to run it here?
(If it works, I would like to ask you to make a PR…)

**Comment by msh9184** [comment]
Hi @sw005320, thank you so much for addressing this issue! :)

First of all, I found out that it was due to the long utterance length of some samples in simulated mixture training data (callhome benchmark: sre+switchboard).

As in the recipe of [your paper](https://arxiv.org/pdf/1909.06247.pdf), setting the maximum length to 50 seconds, with a batch size of 64 and hop size of 10ms, solved the out-of-memory issue.

I used the three 24GB NVIDIA GeForce RTX 3090 GPUs, and my config was as follows:

```
config: conf/train_diar.yaml
iterator_type: sequence
output_dir: exp/diar_train_diar_raw
multiprocessing_distributed: true
max_epoch: 200
grad_clip: 5
grad_clip_type: 2.0
accum_grad: 2
train_dtype: float32
batch_size: 64
valid_batch_size: null
batch_bins: 1000000
valid_batch_bins: null
train_shape_file:
- exp/diar_stats_8k/train/speech_shape
- exp/diar_stats_8k/train/spk_labels_shape
valid_shape_file:
- exp/diar_stats_8k/valid/speech_shape
- exp/diar_stats_8k/valid/spk_labels_shape
batch_type: folded
valid_batch_type: null
fold_length:
- 80000
- 800
sort_in_batch: descending
sort_batch: descending
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/swb_sre_tr_ns2_beta2_100000/wav.scp
    - speech
    - sound
-   - dump/raw/swb_sre_tr_ns2_beta2_100000/espnet_rttm
    - spk_labels
    - rttm
valid_data_path_and_name_and_type:
-   - dump/raw/swb_sre_cv_ns2_beta2_500/wav.scp
    - speech
    - sound
-   - dump/raw/swb_sre_cv_ns2_beta2_500/espnet_rttm
    - spk_labels
    - rttm
optim: adam
optim_conf:
    lr: 0.0002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 100000
num_spk: 2
init: xavier_uniform
model_conf:
    diar_weight: 1.0
    attractor_weight: 1.0
use_preprocessor: true
frontend: default
frontend_conf:
    fs: 8k
    hop_length: 80
specaug: specaug
specaug_conf:
    apply_time_warp: false
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
normalize: global_mvn
normalize_conf:
    stats_file: exp/diar_stats_8k/train/feats_stats.npz
encoder: transformer
encoder_conf:
    input_layer: linear
    num_blocks: 4
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256
    attention_heads: 4
    attention_dropout_rate: 0.1
decoder: linear
label_aggregator: label_aggregator
required:
- output_dir
version: '202301'
distributed: true
```

If I can reproduce the performance of your paper and clean up the scripts, configs, or instructions, I'll try to make a PR so that it can give reference to others. Thank you!
