### ISSUE TITLE
Traceback (most recent call last):   File "pyscripts/utils/calculate_rtf.py", line 113, in <module>     main()   File "pyscripts/utils/calculate_rtf.py", line 90, in main     assert len(audio_durations) == len(end_times), ( AssertionError: (0, 151) # Accounting: time=0 threads=1 # Ended (code 1) at Wed Jan 10 02:02:22 IST 2024, elapsed time 0 seconds

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [espnet/espnet#5617]
I have trained an ASR using espnet2 recipe with the following config:-
```
batch_type: numel
#batch_bins: 12000000
batch_bins: 7000000
accum_grad: 4
#max_epoch: 10
max_epoch: 5000
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
#keep_nbest_models: 3
keep_nbest_models: 8
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31
    interctc_layer_idx: [3, 6, 9,]
    interctc_use_conditioning: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    interctc_weight: 0.5
    length_normalized_loss: false
    extract_feats_in_collect_stats: false

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_url  # Note: If the upstream is changed, please change the input_size in the preencoder.
        path_or_url: https://huggingface.co/s3prl/converted_ckpts/resolve/main/xlsr2_300m.pt
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80
```
I have run the following command during the time of decoding:-
```
./asr.sh --use_lm false --gpu_inference true --inference_nj 1 --stage 12 --stop_stage 12 --train_set train_nodev --valid_set train_dev --test_sets "train_dev test" --asr_exp exp/asr_train_asr_conformer_scctc_raw_bpe30 --inference_config conf/decode_asr.yaml
```
It is giving the following error:-
```
Traceback (most recent call last):
  File "pyscripts/utils/calculate_rtf.py", line 113, in <module>
    main()
  File "pyscripts/utils/calculate_rtf.py", line 90, in main
    assert len(audio_durations) == len(end_times), (
AssertionError: (0, 151)
# Accounting: time=0 threads=1
# Ended (code 1) at Wed Jan 10 02:02:22 IST 2024, elapsed time 0 seconds
```
Previously I have done decoding in the same process with the same dataset but didn't face this error. Can anybody kindly please help me in fixing this error?
